{{config(materialized = "table")}}

WITH NETWORK_MAPPING AS (
    SELECT *
    FROM {{ ref('network_mapping') }}
)

, ATTRIBUTION AS (
    SELECT A.NETWORK_NAME
         , NM.SUPERMETRICS_PARTNER_ID
         , A.CAMPAIGN_NAME
         , A.CAMPAIGN_ID
         , A.ADGROUP_NAME
         , A.ADGROUP_ID
         , A.PLATFORM
         , A.INSTALL_DATE
         , A.INSTALLS
         , A.MATCHED_DEVICES
         , A.PURCHASERS
         , A.PURCHASE_EVENTS
         , A.REVENUE
         , A.USERS_LEVELED_UP
         , A.LEVEL_UP_EVENTS
         , A.LEVEL_UP_COINS_REWARDED
    FROM {{ ref('attribution__installs') }} A
    LEFT JOIN NETWORK_MAPPING NM
      ON A.NETWORK_NAME = NM.ADJUST_NETWORK_NAME
)

, SPEND AS (
    SELECT PARTNER_ID
         , PARTNER_NAME AS NETWORK_NAME
         , CAMPAIGN_NETWORK AS CAMPAIGN_NAME
         , CAMPAIGN_ID_NETWORK AS CAMPAIGN_ID
         , ADGROUP_NETWORK AS ADGROUP_NAME
         , ADGROUP_ID_NETWORK AS ADGROUP_ID
         , PLATFORM
         , DATE AS SPEND_DATE
         , SUM(COST) AS COST
         , SUM(CLICKS) AS CLICKS
         , SUM(IMPRESSIONS) AS IMPRESSIONS
         , SUM(INSTALLS) AS SUPERMETRICS_INSTALLS
    FROM {{ ref('stg_supermetrics__adj_campaign') }}
    GROUP BY PARTNER_ID
         , PARTNER_NAME
         , CAMPAIGN_NETWORK
         , CAMPAIGN_ID_NETWORK
         , ADGROUP_NETWORK
         , ADGROUP_ID_NETWORK
         , PLATFORM
         , DATE
)

-- Campaign-level join (SANs with IDs)
, CAMPAIGN_LEVEL AS (
    SELECT A.NETWORK_NAME
         , A.CAMPAIGN_NAME
         , A.CAMPAIGN_ID
         , A.ADGROUP_NAME
         , A.ADGROUP_ID
         , A.PLATFORM
         , A.INSTALL_DATE AS DATE
         , S.COST
         , S.CLICKS
         , S.IMPRESSIONS
         , S.SUPERMETRICS_INSTALLS
         , A.INSTALLS AS ATTRIBUTION_INSTALLS
         , A.MATCHED_DEVICES
         , A.PURCHASERS
         , A.PURCHASE_EVENTS
         , A.REVENUE
         , A.USERS_LEVELED_UP
         , A.LEVEL_UP_EVENTS
         , A.LEVEL_UP_COINS_REWARDED
         , 'campaign' AS MATCH_LEVEL
    FROM ATTRIBUTION A
    INNER JOIN SPEND S
      ON A.CAMPAIGN_ID = S.CAMPAIGN_ID
      AND A.ADGROUP_ID = S.ADGROUP_ID
      AND A.PLATFORM = S.PLATFORM
      AND A.INSTALL_DATE = S.SPEND_DATE
    WHERE A.CAMPAIGN_ID IS NOT NULL
)

-- Network-level aggregation for non-SANs (no campaign ID)
, ATTRIBUTION_NETWORK_AGG AS (
    SELECT NETWORK_NAME
         , SUPERMETRICS_PARTNER_ID
         , PLATFORM
         , INSTALL_DATE
         , SUM(INSTALLS) AS INSTALLS
         , SUM(MATCHED_DEVICES) AS MATCHED_DEVICES
         , SUM(PURCHASERS) AS PURCHASERS
         , SUM(PURCHASE_EVENTS) AS PURCHASE_EVENTS
         , SUM(REVENUE) AS REVENUE
         , SUM(USERS_LEVELED_UP) AS USERS_LEVELED_UP
         , SUM(LEVEL_UP_EVENTS) AS LEVEL_UP_EVENTS
         , SUM(LEVEL_UP_COINS_REWARDED) AS LEVEL_UP_COINS_REWARDED
    FROM ATTRIBUTION
    WHERE CAMPAIGN_ID IS NULL
    GROUP BY NETWORK_NAME, SUPERMETRICS_PARTNER_ID, PLATFORM, INSTALL_DATE
)

, SPEND_NETWORK_AGG AS (
    SELECT PARTNER_ID
         , NETWORK_NAME
         , PLATFORM
         , SPEND_DATE
         , SUM(COST) AS COST
         , SUM(CLICKS) AS CLICKS
         , SUM(IMPRESSIONS) AS IMPRESSIONS
         , SUM(SUPERMETRICS_INSTALLS) AS SUPERMETRICS_INSTALLS
    FROM SPEND
    GROUP BY PARTNER_ID, NETWORK_NAME, PLATFORM, SPEND_DATE
)

, NETWORK_LEVEL AS (
    SELECT COALESCE(A.NETWORK_NAME, S.NETWORK_NAME) AS NETWORK_NAME
         , NULL AS CAMPAIGN_NAME
         , NULL AS CAMPAIGN_ID
         , NULL AS ADGROUP_NAME
         , NULL AS ADGROUP_ID
         , COALESCE(A.PLATFORM, S.PLATFORM) AS PLATFORM
         , COALESCE(A.INSTALL_DATE, S.SPEND_DATE) AS DATE
         , COALESCE(S.COST, 0) AS COST
         , COALESCE(S.CLICKS, 0) AS CLICKS
         , COALESCE(S.IMPRESSIONS, 0) AS IMPRESSIONS
         , COALESCE(S.SUPERMETRICS_INSTALLS, 0) AS SUPERMETRICS_INSTALLS
         , COALESCE(A.INSTALLS, 0) AS ATTRIBUTION_INSTALLS
         , COALESCE(A.MATCHED_DEVICES, 0) AS MATCHED_DEVICES
         , COALESCE(A.PURCHASERS, 0) AS PURCHASERS
         , COALESCE(A.PURCHASE_EVENTS, 0) AS PURCHASE_EVENTS
         , COALESCE(A.REVENUE, 0) AS REVENUE
         , COALESCE(A.USERS_LEVELED_UP, 0) AS USERS_LEVELED_UP
         , COALESCE(A.LEVEL_UP_EVENTS, 0) AS LEVEL_UP_EVENTS
         , COALESCE(A.LEVEL_UP_COINS_REWARDED, 0) AS LEVEL_UP_COINS_REWARDED
         , 'network' AS MATCH_LEVEL
    FROM ATTRIBUTION_NETWORK_AGG A
    FULL OUTER JOIN SPEND_NETWORK_AGG S
      ON A.SUPERMETRICS_PARTNER_ID = S.PARTNER_ID
      AND A.PLATFORM = S.PLATFORM
      AND A.INSTALL_DATE = S.SPEND_DATE
)

, COMBINED AS (
    SELECT * FROM CAMPAIGN_LEVEL
    UNION ALL
    SELECT * FROM NETWORK_LEVEL
)

SELECT NETWORK_NAME
     , CAMPAIGN_NAME
     , CAMPAIGN_ID
     , ADGROUP_NAME
     , ADGROUP_ID
     , PLATFORM
     , DATE
     , COALESCE(COST, 0) AS COST
     , COALESCE(CLICKS, 0) AS CLICKS
     , COALESCE(IMPRESSIONS, 0) AS IMPRESSIONS
     , COALESCE(SUPERMETRICS_INSTALLS, 0) AS SUPERMETRICS_INSTALLS
     , COALESCE(ATTRIBUTION_INSTALLS, 0) AS ATTRIBUTION_INSTALLS
     , COALESCE(MATCHED_DEVICES, 0) AS MATCHED_DEVICES
     , COALESCE(PURCHASERS, 0) AS PURCHASERS
     , COALESCE(PURCHASE_EVENTS, 0) AS PURCHASE_EVENTS
     , COALESCE(REVENUE, 0) AS REVENUE
     , COALESCE(USERS_LEVELED_UP, 0) AS USERS_LEVELED_UP
     , COALESCE(LEVEL_UP_EVENTS, 0) AS LEVEL_UP_EVENTS
     , COALESCE(LEVEL_UP_COINS_REWARDED, 0) AS LEVEL_UP_COINS_REWARDED
     , MATCH_LEVEL
     , IFF(COST > 0, COST / NULLIF(ATTRIBUTION_INSTALLS, 0), NULL) AS CPI
     , IFF(COST > 0, REVENUE / NULLIF(COST, 0), NULL) AS ROAS
FROM COMBINED
ORDER BY DATE DESC
     , COST DESC
