{{config(materialized = "table")}}

WITH NETWORK_MAPPING AS (
    SELECT *
    FROM {{ ref('network_mapping') }}
)

, ATTRIBUTION AS (
    SELECT A.NETWORK_NAME
         , NM.SUPERMETRICS_PARTNER_ID
         , A.CAMPAIGN_NAME
         , A.ADGROUP_NAME
         , A.PLATFORM
         , A.INSTALL_DATE
         , A.INSTALLS
         , A.MATCHED_DEVICES
         , A.PURCHASERS
         , A.PURCHASE_EVENTS
         , A.REVENUE
         , A.USERS_LEVELED_UP
         , A.LEVEL_UP_EVENTS
         , A.LEVEL_UP_COINS_REWARDED
    FROM {{ ref('attribution__installs') }} A
    LEFT JOIN NETWORK_MAPPING NM
      ON A.NETWORK_NAME = NM.ADJUST_NETWORK_NAME
)

, SPEND AS (
    SELECT PARTNER_ID
         , PARTNER_NAME AS NETWORK_NAME
         , CAMPAIGN_NETWORK AS CAMPAIGN_NAME
         , ADGROUP_NETWORK AS ADGROUP_NAME
         , PLATFORM
         , DATE AS SPEND_DATE
         , SUM(COST) AS COST
         , SUM(CLICKS) AS CLICKS
         , SUM(IMPRESSIONS) AS IMPRESSIONS
         , SUM(INSTALLS) AS SUPERMETRICS_INSTALLS
    FROM {{ ref('stg_supermetrics__adj_campaign') }}
    GROUP BY PARTNER_ID
         , PARTNER_NAME
         , CAMPAIGN_NETWORK
         , ADGROUP_NETWORK
         , PLATFORM
         , DATE
)

, JOINED AS (
    SELECT COALESCE(A.NETWORK_NAME, S.NETWORK_NAME) AS NETWORK_NAME
         , COALESCE(A.CAMPAIGN_NAME, S.CAMPAIGN_NAME) AS CAMPAIGN_NAME
         , COALESCE(A.ADGROUP_NAME, S.ADGROUP_NAME) AS ADGROUP_NAME
         , COALESCE(A.PLATFORM, S.PLATFORM) AS PLATFORM
         , COALESCE(A.INSTALL_DATE, S.SPEND_DATE) AS DATE
         , COALESCE(S.COST, 0) AS COST
         , COALESCE(S.CLICKS, 0) AS CLICKS
         , COALESCE(S.IMPRESSIONS, 0) AS IMPRESSIONS
         , COALESCE(S.SUPERMETRICS_INSTALLS, 0) AS SUPERMETRICS_INSTALLS
         , COALESCE(A.INSTALLS, 0) AS ATTRIBUTION_INSTALLS
         , COALESCE(A.MATCHED_DEVICES, 0) AS MATCHED_DEVICES
         , COALESCE(A.PURCHASERS, 0) AS PURCHASERS
         , COALESCE(A.PURCHASE_EVENTS, 0) AS PURCHASE_EVENTS
         , COALESCE(A.REVENUE, 0) AS REVENUE
         , COALESCE(A.USERS_LEVELED_UP, 0) AS USERS_LEVELED_UP
         , COALESCE(A.LEVEL_UP_EVENTS, 0) AS LEVEL_UP_EVENTS
         , COALESCE(A.LEVEL_UP_COINS_REWARDED, 0) AS LEVEL_UP_COINS_REWARDED
    FROM ATTRIBUTION A
    FULL OUTER JOIN SPEND S
      ON A.SUPERMETRICS_PARTNER_ID = S.PARTNER_ID
      AND A.CAMPAIGN_NAME = S.CAMPAIGN_NAME
      AND A.ADGROUP_NAME = S.ADGROUP_NAME
      AND A.PLATFORM = S.PLATFORM
      AND A.INSTALL_DATE = S.SPEND_DATE
)

SELECT NETWORK_NAME
     , CAMPAIGN_NAME
     , ADGROUP_NAME
     , PLATFORM
     , DATE
     , COST
     , CLICKS
     , IMPRESSIONS
     , SUPERMETRICS_INSTALLS
     , ATTRIBUTION_INSTALLS
     , MATCHED_DEVICES
     , PURCHASERS
     , PURCHASE_EVENTS
     , REVENUE
     , USERS_LEVELED_UP
     , LEVEL_UP_EVENTS
     , LEVEL_UP_COINS_REWARDED
     , IFF(COST > 0, COST / NULLIF(ATTRIBUTION_INSTALLS, 0), NULL) AS CPI
     , IFF(COST > 0, REVENUE / NULLIF(COST, 0), NULL) AS ROAS
FROM JOINED
ORDER BY DATE DESC
     , COST DESC
