{{config(materialized = "table")}}


WITH INSTALLS AS (
    SELECT *
    FROM {{ ref('v_stg_adjust__installs') }}
    {% if is_incremental() %}
    WHERE INSTALL_TIMESTAMP >= (SELECT MAX(INSTALL_DATE) FROM {{ this }})
    {% endif %}
)

, DEVICE_MAPPING AS (
    SELECT *
    FROM {{ ref('int_adjust_amplitude__device_mapping') }}
)

, AMPLITUDE_EVENTS AS (
    SELECT *
    FROM {{ ref('v_stg_amplitude__events') }}
    {% if is_incremental() %}
    WHERE EVENT_TIME >= (SELECT MAX(INSTALL_DATE) FROM {{ this }})
    {% endif %}
)

, REVENUE_SUMMARY AS (
    SELECT *
    FROM {{ ref('int_revenue__user_summary') }}
)

, BASE_INSTALLS AS (
    SELECT AI.NETWORK_NAME
         , AI.CAMPAIGN_NAME
         , AI.CAMPAIGN_ID
         , AI.ADGROUP_NAME
         , AI.ADGROUP_ID
         , AI.PLATFORM
         , CAST(AI.INSTALL_TIMESTAMP AS DATE) AS INSTALL_DATE
         , AI.DEVICE_ID
         , M.AMPLITUDE_USER_ID
    FROM INSTALLS AI
    LEFT JOIN DEVICE_MAPPING M 
      ON AI.DEVICE_ID = M.ADJUST_DEVICE_ID
      AND AI.PLATFORM = M.PLATFORM
)

-- FIX: Aggregate revenue at USER level first, then join to installs
-- This prevents fan-out when users have multiple devices
, USER_REVENUE AS (
    SELECT RS.USER_ID
         , RS.PURCHASE_COUNT
         , RS.TOTAL_REVENUE
    FROM REVENUE_SUMMARY RS
)

, REVENUE_ATTRIBUTED AS (
    SELECT BI.NETWORK_NAME
         , BI.CAMPAIGN_ID
         , BI.ADGROUP_ID
         , BI.INSTALL_DATE
         , COUNT(DISTINCT BI.AMPLITUDE_USER_ID) AS PURCHASERS
         , SUM(UR.PURCHASE_COUNT) AS PURCHASE_EVENTS
         , SUM(UR.TOTAL_REVENUE) AS REVENUE
    FROM BASE_INSTALLS BI
    INNER JOIN USER_REVENUE UR 
      ON BI.AMPLITUDE_USER_ID = UR.USER_ID
    WHERE BI.AMPLITUDE_USER_ID IS NOT NULL
    GROUP BY BI.NETWORK_NAME
         , BI.CAMPAIGN_ID
         , BI.ADGROUP_ID
         , BI.INSTALL_DATE
)

-- FIX: Aggregate level-up events at USER level first, then join to installs
-- This prevents fan-out when users have multiple devices
, USER_LEVEL_UPS AS (
    SELECT AE.USER_ID
         , COUNT(*) AS LEVEL_UP_EVENTS
         , SUM(PARSE_JSON(AE.EVENT_PROPERTIES):v::INTEGER) AS LEVEL_UP_COINS_REWARDED
    FROM AMPLITUDE_EVENTS AE
    WHERE AE.EVENT_TYPE = 'LevelUpCoinsRewarded'
    GROUP BY AE.USER_ID
)

, LEVEL_UP_ATTRIBUTED AS (
    SELECT BI.NETWORK_NAME
         , BI.CAMPAIGN_ID
         , BI.ADGROUP_ID
         , BI.INSTALL_DATE
         , COUNT(DISTINCT BI.AMPLITUDE_USER_ID) AS USERS_LEVELED_UP
         , SUM(UL.LEVEL_UP_EVENTS) AS LEVEL_UP_EVENTS
         , SUM(UL.LEVEL_UP_COINS_REWARDED) AS LEVEL_UP_COINS_REWARDED
    FROM BASE_INSTALLS BI
    INNER JOIN USER_LEVEL_UPS UL 
      ON BI.AMPLITUDE_USER_ID = UL.USER_ID
    WHERE BI.AMPLITUDE_USER_ID IS NOT NULL
    GROUP BY BI.NETWORK_NAME
         , BI.CAMPAIGN_ID
         , BI.ADGROUP_ID
         , BI.INSTALL_DATE
)

, INSTALL_SUMMARY AS (
    SELECT NETWORK_NAME
         , CAMPAIGN_NAME
         , CAMPAIGN_ID
         , ADGROUP_NAME
         , ADGROUP_ID
         , PLATFORM
         , INSTALL_DATE
         , COUNT(DISTINCT DEVICE_ID) AS INSTALLS
         , COUNT(DISTINCT AMPLITUDE_USER_ID) AS MATCHED_DEVICES
    FROM BASE_INSTALLS
    GROUP BY NETWORK_NAME
         , CAMPAIGN_NAME
         , CAMPAIGN_ID
         , ADGROUP_NAME
         , ADGROUP_ID
         , PLATFORM
         , INSTALL_DATE
)

SELECT IS_TABLE.NETWORK_NAME
     , IS_TABLE.CAMPAIGN_NAME
     , IS_TABLE.CAMPAIGN_ID
     , IS_TABLE.ADGROUP_NAME
     , IS_TABLE.ADGROUP_ID
     , IS_TABLE.PLATFORM
     , IS_TABLE.INSTALL_DATE
     , IS_TABLE.INSTALLS
     , IS_TABLE.MATCHED_DEVICES
     , COALESCE(RA.PURCHASERS, 0) AS PURCHASERS
     , COALESCE(RA.PURCHASE_EVENTS, 0) AS PURCHASE_EVENTS
     , COALESCE(RA.REVENUE, 0) AS REVENUE
     , COALESCE(LA.USERS_LEVELED_UP, 0) AS USERS_LEVELED_UP
     , COALESCE(LA.LEVEL_UP_EVENTS, 0) AS LEVEL_UP_EVENTS
     , COALESCE(LA.LEVEL_UP_COINS_REWARDED, 0) AS LEVEL_UP_COINS_REWARDED
FROM INSTALL_SUMMARY IS_TABLE
LEFT JOIN REVENUE_ATTRIBUTED RA 
  ON COALESCE(IS_TABLE.NETWORK_NAME, '') = COALESCE(RA.NETWORK_NAME, '')
  AND COALESCE(IS_TABLE.CAMPAIGN_ID, '') = COALESCE(RA.CAMPAIGN_ID, '')
  AND COALESCE(IS_TABLE.ADGROUP_ID, '') = COALESCE(RA.ADGROUP_ID, '')
  AND IS_TABLE.INSTALL_DATE = RA.INSTALL_DATE
LEFT JOIN LEVEL_UP_ATTRIBUTED LA 
  ON COALESCE(IS_TABLE.NETWORK_NAME, '') = COALESCE(LA.NETWORK_NAME, '')
  AND COALESCE(IS_TABLE.CAMPAIGN_ID, '') = COALESCE(LA.CAMPAIGN_ID, '')
  AND COALESCE(IS_TABLE.ADGROUP_ID, '') = COALESCE(LA.ADGROUP_ID, '')
  AND IS_TABLE.INSTALL_DATE = LA.INSTALL_DATE
ORDER BY INSTALL_DATE DESC
     , INSTALLS DESC
