{{config(materialized = "table")}}


WITH INSTALLS AS (
    SELECT *
    FROM {{ ref('v_stg_adjust__installs') }}
    {% if is_incremental() %}
    WHERE INSTALL_TIMESTAMP >= (SELECT MAX(INSTALL_DATE) FROM {{ this }})
    {% endif %}
)

, DEVICE_MAPPING AS (
    SELECT *
    FROM {{ ref('int_adjust_amplitude__device_mapping') }}
)

, AMPLITUDE_EVENTS AS (
    SELECT *
    FROM {{ ref('v_stg_amplitude__events') }}
    {% if is_incremental() %}
    WHERE EVENT_TIME >= (SELECT MAX(INSTALL_DATE) FROM {{ this }})
    {% endif %}
)

, REVENUE_SUMMARY AS (
    SELECT *
    FROM {{ ref('int_revenue__user_summary') }}
)

-- Join installs to device mapping, including FIRST_SEEN_AT for attribution window
, BASE_INSTALLS AS (
    SELECT AI.AD_PARTNER
         , AI.NETWORK_NAME
         , AI.CAMPAIGN_NAME
         , AI.CAMPAIGN_ID
         , AI.ADGROUP_NAME
         , AI.ADGROUP_ID
         , AI.PLATFORM
         , AI.INSTALL_TIMESTAMP
         , CAST(AI.INSTALL_TIMESTAMP AS DATE) AS INSTALL_DATE
         , AI.DEVICE_ID
         , M.AMPLITUDE_USER_ID
         , M.FIRST_SEEN_AT
         , DATEDIFF('day', AI.INSTALL_TIMESTAMP, M.FIRST_SEEN_AT) AS DAYS_TO_FIRST_ACTIVITY
    FROM INSTALLS AI
    LEFT JOIN DEVICE_MAPPING M 
      ON AI.DEVICE_ID = M.ADJUST_DEVICE_ID
      AND AI.PLATFORM = M.PLATFORM
)

-- Identify the FIRST install per user to prevent revenue fan-out
-- Revenue should only be attributed once per user, to their earliest install
, BASE_INSTALLS_WITH_RANK AS (
    SELECT *
         , ROW_NUMBER() OVER (
             PARTITION BY AMPLITUDE_USER_ID
             ORDER BY INSTALL_DATE ASC
                    , DEVICE_ID ASC
           ) AS USER_INSTALL_RANK
    FROM BASE_INSTALLS
    WHERE AMPLITUDE_USER_ID IS NOT NULL
)

-- User's first install only, with valid attribution window (7 days)
-- If user first appeared on device more than 7 days after install,
-- the original installer is likely gone and we should not attribute revenue
, FIRST_USER_INSTALLS AS (
    SELECT AD_PARTNER
         , NETWORK_NAME
         , CAMPAIGN_ID
         , ADGROUP_ID
         , PLATFORM
         , INSTALL_DATE
         , AMPLITUDE_USER_ID
         , DAYS_TO_FIRST_ACTIVITY
    FROM BASE_INSTALLS_WITH_RANK
    WHERE USER_INSTALL_RANK = 1
      AND DAYS_TO_FIRST_ACTIVITY <= 7
)

-- Aggregate revenue at USER level
, USER_REVENUE AS (
    SELECT RS.USER_ID
         , RS.PURCHASE_COUNT
         , RS.TOTAL_REVENUE
    FROM REVENUE_SUMMARY RS
)

-- Join revenue only to FIRST install per user within attribution window
, REVENUE_ATTRIBUTED AS (
    SELECT FI.AD_PARTNER
         , FI.NETWORK_NAME
         , FI.CAMPAIGN_ID
         , FI.ADGROUP_ID
         , FI.PLATFORM
         , FI.INSTALL_DATE
         , COUNT(DISTINCT FI.AMPLITUDE_USER_ID) AS PURCHASERS
         , SUM(UR.PURCHASE_COUNT) AS PURCHASE_EVENTS
         , SUM(UR.TOTAL_REVENUE) AS REVENUE
    FROM FIRST_USER_INSTALLS FI
    INNER JOIN USER_REVENUE UR 
      ON FI.AMPLITUDE_USER_ID = UR.USER_ID
    GROUP BY FI.AD_PARTNER
         , FI.NETWORK_NAME
         , FI.CAMPAIGN_ID
         , FI.ADGROUP_ID
         , FI.PLATFORM
         , FI.INSTALL_DATE
)

-- Aggregate level-up events at USER level
, USER_LEVEL_UPS AS (
    SELECT AE.USER_ID
         , COUNT(*) AS LEVEL_UP_EVENTS
         , SUM(PARSE_JSON(AE.EVENT_PROPERTIES):v::INTEGER) AS LEVEL_UP_COINS_REWARDED
    FROM AMPLITUDE_EVENTS AE
    WHERE AE.EVENT_TYPE = 'LevelUpCoinsRewarded'
    GROUP BY AE.USER_ID
)

-- Join level-ups only to FIRST install per user within attribution window
, LEVEL_UP_ATTRIBUTED AS (
    SELECT FI.AD_PARTNER
         , FI.NETWORK_NAME
         , FI.CAMPAIGN_ID
         , FI.ADGROUP_ID
         , FI.PLATFORM
         , FI.INSTALL_DATE
         , COUNT(DISTINCT FI.AMPLITUDE_USER_ID) AS USERS_LEVELED_UP
         , SUM(UL.LEVEL_UP_EVENTS) AS LEVEL_UP_EVENTS
         , SUM(UL.LEVEL_UP_COINS_REWARDED) AS LEVEL_UP_COINS_REWARDED
    FROM FIRST_USER_INSTALLS FI
    INNER JOIN USER_LEVEL_UPS UL 
      ON FI.AMPLITUDE_USER_ID = UL.USER_ID
    GROUP BY FI.AD_PARTNER
         , FI.NETWORK_NAME
         , FI.CAMPAIGN_ID
         , FI.ADGROUP_ID
         , FI.PLATFORM
         , FI.INSTALL_DATE
)

, INSTALL_SUMMARY AS (
    SELECT AD_PARTNER
         , NETWORK_NAME
         , CAMPAIGN_NAME
         , CAMPAIGN_ID
         , ADGROUP_NAME
         , ADGROUP_ID
         , PLATFORM
         , INSTALL_DATE
         , COUNT(DISTINCT DEVICE_ID) AS INSTALLS
         , COUNT(DISTINCT AMPLITUDE_USER_ID) AS MATCHED_DEVICES
    FROM BASE_INSTALLS
    GROUP BY AD_PARTNER
         , NETWORK_NAME
         , CAMPAIGN_NAME
         , CAMPAIGN_ID
         , ADGROUP_NAME
         , ADGROUP_ID
         , PLATFORM
         , INSTALL_DATE
)

SELECT IS_TABLE.AD_PARTNER
     , IS_TABLE.NETWORK_NAME
     , IS_TABLE.CAMPAIGN_NAME
     , IS_TABLE.CAMPAIGN_ID
     , IS_TABLE.ADGROUP_NAME
     , IS_TABLE.ADGROUP_ID
     , IS_TABLE.PLATFORM
     , IS_TABLE.INSTALL_DATE
     , IS_TABLE.INSTALLS
     , IS_TABLE.MATCHED_DEVICES
     , COALESCE(RA.PURCHASERS, 0) AS PURCHASERS
     , COALESCE(RA.PURCHASE_EVENTS, 0) AS PURCHASE_EVENTS
     , COALESCE(RA.REVENUE, 0) AS REVENUE
     , COALESCE(LA.USERS_LEVELED_UP, 0) AS USERS_LEVELED_UP
     , COALESCE(LA.LEVEL_UP_EVENTS, 0) AS LEVEL_UP_EVENTS
     , COALESCE(LA.LEVEL_UP_COINS_REWARDED, 0) AS LEVEL_UP_COINS_REWARDED
FROM INSTALL_SUMMARY IS_TABLE
LEFT JOIN REVENUE_ATTRIBUTED RA 
  ON COALESCE(IS_TABLE.AD_PARTNER, '') = COALESCE(RA.AD_PARTNER, '')
  AND COALESCE(IS_TABLE.NETWORK_NAME, '') = COALESCE(RA.NETWORK_NAME, '')
  AND COALESCE(IS_TABLE.CAMPAIGN_ID, '') = COALESCE(RA.CAMPAIGN_ID, '')
  AND COALESCE(IS_TABLE.ADGROUP_ID, '') = COALESCE(RA.ADGROUP_ID, '')
  AND IS_TABLE.PLATFORM = RA.PLATFORM
  AND IS_TABLE.INSTALL_DATE = RA.INSTALL_DATE
LEFT JOIN LEVEL_UP_ATTRIBUTED LA 
  ON COALESCE(IS_TABLE.AD_PARTNER, '') = COALESCE(LA.AD_PARTNER, '')
  AND COALESCE(IS_TABLE.NETWORK_NAME, '') = COALESCE(LA.NETWORK_NAME, '')
  AND COALESCE(IS_TABLE.CAMPAIGN_ID, '') = COALESCE(LA.CAMPAIGN_ID, '')
  AND COALESCE(IS_TABLE.ADGROUP_ID, '') = COALESCE(LA.ADGROUP_ID, '')
  AND IS_TABLE.PLATFORM = LA.PLATFORM
  AND IS_TABLE.INSTALL_DATE = LA.INSTALL_DATE
ORDER BY INSTALL_DATE DESC
     , INSTALLS DESC
