-- mart_campaign_performance_full_mta.sql
-- Comprehensive campaign-level performance metrics with ALL attribution models
-- Compare Adjust last-touch attribution vs 5 MTA models side-by-side
--
-- Attribution Models Included:
-- 1. ADJUST: Adjust's native last-touch attribution (baseline)
-- 2. LAST_TOUCH: MTA last-touch (for validation against Adjust)
-- 3. FIRST_TOUCH: 100% credit to first touchpoint
-- 4. LINEAR: Equal credit across all touchpoints
-- 5. TIME_DECAY: Exponential decay (3-day half-life) - RECOMMENDED
-- 6. POSITION_BASED: U-shaped (40% first, 40% last, 20% middle)
--
-- Includes for each model: Installs, Revenue (D7/D30/Total), Retention (D1/D7/D30), Payers
-- Plus derived metrics: CPI, ROAS, ARPI, ARPPU, Retention Rates, Payer Conversion
--
-- Grain: One row per AD_PARTNER/CAMPAIGN_NAME/PLATFORM/DATE

{{ config(
    materialized='incremental',
    unique_key=['AD_PARTNER', 'CAMPAIGN_NAME', 'PLATFORM', 'DATE'],
    incremental_strategy='merge',
    on_schema_change='append_new_columns',
    tags=['mart', 'performance', 'mta']
) }}

-- =============================================
-- SPEND DATA (from Adjust API REPORT_DAILY)
-- Aggregated to campaign level
-- =============================================
WITH partner_map AS (
    -- Map Adjust network names (e.g., "Facebook Installs" → "Meta")
    SELECT DISTINCT
        ADJUST_NETWORK_NAME AS PARTNER_NAME
        , AD_PARTNER
    FROM {{ ref('network_mapping') }}
    WHERE AD_PARTNER IS NOT NULL

    UNION

    -- Map "(Ad Spend)" suffixed names (e.g., "Facebook (Ad Spend)" → "Meta")
    SELECT DISTINCT
        SUPERMETRICS_PARTNER_NAME || ' (Ad Spend)' AS PARTNER_NAME
        , AD_PARTNER
    FROM {{ ref('network_mapping') }}
    WHERE AD_PARTNER IS NOT NULL
)

, spend_data AS (
    SELECT
        s.DATE
        , COALESCE(pm.AD_PARTNER, s.PARTNER_NAME) AS AD_PARTNER
        , s.CAMPAIGN_NETWORK AS CAMPAIGN_NAME
        , s.PLATFORM
        , SUM(s.NETWORK_COST) AS COST
        , SUM(s.CLICKS) AS CLICKS
        , SUM(s.IMPRESSIONS) AS IMPRESSIONS
        , SUM(s.INSTALLS) AS ADJUST_NETWORK_INSTALLS
    FROM {{ ref('stg_adjust__report_daily') }} s
    LEFT JOIN partner_map pm ON s.PARTNER_NAME = pm.PARTNER_NAME
    WHERE s.DATE IS NOT NULL
    {% if is_incremental() %}
        AND s.DATE >= DATEADD(day, -3, (SELECT MAX(DATE) FROM {{ this }}))
    {% endif %}
    GROUP BY 1, 2, 3, 4
)

-- =============================================
-- ADJUST ATTRIBUTION (baseline last-touch from Adjust)
-- =============================================
, adjust_attribution AS (
    SELECT * FROM {{ ref('int_user_cohort__attribution') }}
    {% if is_incremental() %}
        WHERE INSTALL_DATE >= DATEADD(day, -35, (SELECT MAX(DATE) FROM {{ this }}))
    {% endif %}
)

-- =============================================
-- USER METRICS (revenue, retention, payers)
-- =============================================
, user_metrics AS (
    SELECT
        USER_ID
        , PLATFORM
        , D7_REVENUE
        , D30_REVENUE
        , TOTAL_REVENUE
        , D7_PURCHASE_REVENUE
        , D30_PURCHASE_REVENUE
        , TOTAL_PURCHASE_REVENUE
        , D7_AD_REVENUE
        , D30_AD_REVENUE
        , TOTAL_AD_REVENUE
        , IS_D7_PAYER
        , IS_D30_PAYER
        , IS_PAYER
        , D1_RETAINED
        , D7_RETAINED
        , D30_RETAINED
        , D1_MATURED
        , D7_MATURED
        , D30_MATURED
    FROM {{ ref('int_user_cohort__metrics') }}
    {% if is_incremental() %}
        WHERE INSTALL_DATE >= DATEADD(day, -35, (SELECT MAX(DATE) FROM {{ this }}))
    {% endif %}
)

-- =============================================
-- ADJUST METRICS AGGREGATED (baseline) at Campaign level
-- =============================================
, adjust_metrics AS (
    SELECT
        a.INSTALL_DATE AS DATE
        , a.AD_PARTNER
        , a.CAMPAIGN_NAME
        , a.PLATFORM

        -- Adjust attribution counts (raw counts, not fractional)
        , COUNT(DISTINCT a.USER_ID) AS ADJUST_INSTALLS

        -- Revenue attributed via Adjust
        , SUM(COALESCE(m.TOTAL_REVENUE, 0)) AS ADJUST_TOTAL_REVENUE
        , SUM(COALESCE(m.D7_REVENUE, 0)) AS ADJUST_D7_REVENUE
        , SUM(COALESCE(m.D30_REVENUE, 0)) AS ADJUST_D30_REVENUE
        , SUM(COALESCE(m.TOTAL_PURCHASE_REVENUE, 0)) AS ADJUST_TOTAL_PURCHASE_REVENUE
        , SUM(COALESCE(m.D7_PURCHASE_REVENUE, 0)) AS ADJUST_D7_PURCHASE_REVENUE
        , SUM(COALESCE(m.D30_PURCHASE_REVENUE, 0)) AS ADJUST_D30_PURCHASE_REVENUE
        , SUM(COALESCE(m.TOTAL_AD_REVENUE, 0)) AS ADJUST_TOTAL_AD_REVENUE
        , SUM(COALESCE(m.D7_AD_REVENUE, 0)) AS ADJUST_D7_AD_REVENUE
        , SUM(COALESCE(m.D30_AD_REVENUE, 0)) AS ADJUST_D30_AD_REVENUE

        -- Payers attributed via Adjust
        , SUM(COALESCE(m.IS_PAYER, 0)) AS ADJUST_TOTAL_PAYERS
        , SUM(COALESCE(m.IS_D7_PAYER, 0)) AS ADJUST_D7_PAYERS
        , SUM(COALESCE(m.IS_D30_PAYER, 0)) AS ADJUST_D30_PAYERS

        -- Retention attributed via Adjust
        , SUM(COALESCE(m.D1_RETAINED, 0)) AS ADJUST_D1_RETAINED
        , SUM(COALESCE(m.D7_RETAINED, 0)) AS ADJUST_D7_RETAINED
        , SUM(COALESCE(m.D30_RETAINED, 0)) AS ADJUST_D30_RETAINED
        , SUM(COALESCE(m.D1_MATURED, 0)) AS ADJUST_D1_MATURED
        , SUM(COALESCE(m.D7_MATURED, 0)) AS ADJUST_D7_MATURED
        , SUM(COALESCE(m.D30_MATURED, 0)) AS ADJUST_D30_MATURED

    FROM adjust_attribution a
    LEFT JOIN user_metrics m
        ON a.USER_ID = m.USER_ID
        AND a.PLATFORM = m.PLATFORM
    WHERE a.INSTALL_DATE IS NOT NULL
    GROUP BY 1, 2, 3, 4
)

-- =============================================
-- MTA TOUCHPOINT CREDITS
-- =============================================
, touchpoint_credits AS (
    SELECT
        tc.DEVICE_ID
        , tc.PLATFORM
        , tc.AD_PARTNER
        , tc.CAMPAIGN_NAME
        , CAST(tc.INSTALL_TIMESTAMP AS DATE) AS INSTALL_DATE
        , tc.CREDIT_LAST_TOUCH
        , tc.CREDIT_FIRST_TOUCH
        , tc.CREDIT_LINEAR
        , tc.CREDIT_TIME_DECAY
        , tc.CREDIT_POSITION_BASED
    FROM {{ ref('int_mta__touchpoint_credit') }} tc
    {% if is_incremental() %}
        WHERE CAST(tc.INSTALL_TIMESTAMP AS DATE) >= DATEADD(day, -35, (SELECT MAX(DATE) FROM {{ this }}))
    {% endif %}
)

-- =============================================
-- DEVICE TO USER MAPPING
-- =============================================
, device_mapping AS (
    SELECT
        ADJUST_DEVICE_ID
        , AMPLITUDE_USER_ID
        , PLATFORM
    FROM {{ ref('int_adjust_amplitude__device_mapping') }}
)

-- =============================================
-- MTA TOUCHPOINTS WITH USER METRICS
-- =============================================
, touchpoints_with_metrics AS (
    SELECT
        tc.*
        , dm.AMPLITUDE_USER_ID
        -- Revenue
        , COALESCE(um.D7_REVENUE, 0) AS USER_D7_REVENUE
        , COALESCE(um.D30_REVENUE, 0) AS USER_D30_REVENUE
        , COALESCE(um.TOTAL_REVENUE, 0) AS USER_TOTAL_REVENUE
        , COALESCE(um.D7_PURCHASE_REVENUE, 0) AS USER_D7_PURCHASE_REVENUE
        , COALESCE(um.D30_PURCHASE_REVENUE, 0) AS USER_D30_PURCHASE_REVENUE
        , COALESCE(um.TOTAL_PURCHASE_REVENUE, 0) AS USER_TOTAL_PURCHASE_REVENUE
        , COALESCE(um.D7_AD_REVENUE, 0) AS USER_D7_AD_REVENUE
        , COALESCE(um.D30_AD_REVENUE, 0) AS USER_D30_AD_REVENUE
        , COALESCE(um.TOTAL_AD_REVENUE, 0) AS USER_TOTAL_AD_REVENUE
        -- Payers
        , COALESCE(um.IS_D7_PAYER, 0) AS USER_IS_D7_PAYER
        , COALESCE(um.IS_D30_PAYER, 0) AS USER_IS_D30_PAYER
        , COALESCE(um.IS_PAYER, 0) AS USER_IS_PAYER
        -- Retention
        , COALESCE(um.D1_RETAINED, 0) AS USER_D1_RETAINED
        , COALESCE(um.D7_RETAINED, 0) AS USER_D7_RETAINED
        , COALESCE(um.D30_RETAINED, 0) AS USER_D30_RETAINED
        , COALESCE(um.D1_MATURED, 0) AS USER_D1_MATURED
        , COALESCE(um.D7_MATURED, 0) AS USER_D7_MATURED
        , COALESCE(um.D30_MATURED, 0) AS USER_D30_MATURED
    FROM touchpoint_credits tc
    LEFT JOIN device_mapping dm
        ON tc.DEVICE_ID = dm.ADJUST_DEVICE_ID
        AND tc.PLATFORM = dm.PLATFORM
    LEFT JOIN user_metrics um
        ON dm.AMPLITUDE_USER_ID = um.USER_ID
        AND dm.PLATFORM = um.PLATFORM
)

-- =============================================
-- MTA METRICS AGGREGATED (all 5 models) at Campaign level
-- =============================================
, mta_metrics AS (
    SELECT
        INSTALL_DATE AS DATE
        , AD_PARTNER
        , CAMPAIGN_NAME
        , PLATFORM

        -- =============================================
        -- INSTALLS BY MODEL
        -- =============================================
        , SUM(CREDIT_LAST_TOUCH) AS MTA_LAST_TOUCH_INSTALLS
        , SUM(CREDIT_FIRST_TOUCH) AS MTA_FIRST_TOUCH_INSTALLS
        , SUM(CREDIT_LINEAR) AS MTA_LINEAR_INSTALLS
        , SUM(CREDIT_TIME_DECAY) AS MTA_TIME_DECAY_INSTALLS
        , SUM(CREDIT_POSITION_BASED) AS MTA_POSITION_BASED_INSTALLS

        -- =============================================
        -- TOTAL REVENUE BY MODEL
        -- =============================================
        , SUM(CREDIT_LAST_TOUCH * USER_TOTAL_REVENUE) AS MTA_LAST_TOUCH_TOTAL_REVENUE
        , SUM(CREDIT_FIRST_TOUCH * USER_TOTAL_REVENUE) AS MTA_FIRST_TOUCH_TOTAL_REVENUE
        , SUM(CREDIT_LINEAR * USER_TOTAL_REVENUE) AS MTA_LINEAR_TOTAL_REVENUE
        , SUM(CREDIT_TIME_DECAY * USER_TOTAL_REVENUE) AS MTA_TIME_DECAY_TOTAL_REVENUE
        , SUM(CREDIT_POSITION_BASED * USER_TOTAL_REVENUE) AS MTA_POSITION_BASED_TOTAL_REVENUE

        -- =============================================
        -- D7 REVENUE BY MODEL
        -- =============================================
        , SUM(CREDIT_LAST_TOUCH * USER_D7_REVENUE) AS MTA_LAST_TOUCH_D7_REVENUE
        , SUM(CREDIT_FIRST_TOUCH * USER_D7_REVENUE) AS MTA_FIRST_TOUCH_D7_REVENUE
        , SUM(CREDIT_LINEAR * USER_D7_REVENUE) AS MTA_LINEAR_D7_REVENUE
        , SUM(CREDIT_TIME_DECAY * USER_D7_REVENUE) AS MTA_TIME_DECAY_D7_REVENUE
        , SUM(CREDIT_POSITION_BASED * USER_D7_REVENUE) AS MTA_POSITION_BASED_D7_REVENUE

        -- =============================================
        -- D30 REVENUE BY MODEL
        -- =============================================
        , SUM(CREDIT_LAST_TOUCH * USER_D30_REVENUE) AS MTA_LAST_TOUCH_D30_REVENUE
        , SUM(CREDIT_FIRST_TOUCH * USER_D30_REVENUE) AS MTA_FIRST_TOUCH_D30_REVENUE
        , SUM(CREDIT_LINEAR * USER_D30_REVENUE) AS MTA_LINEAR_D30_REVENUE
        , SUM(CREDIT_TIME_DECAY * USER_D30_REVENUE) AS MTA_TIME_DECAY_D30_REVENUE
        , SUM(CREDIT_POSITION_BASED * USER_D30_REVENUE) AS MTA_POSITION_BASED_D30_REVENUE

        -- =============================================
        -- PURCHASE REVENUE BY MODEL (Time-Decay only for brevity)
        -- =============================================
        , SUM(CREDIT_TIME_DECAY * USER_TOTAL_PURCHASE_REVENUE) AS MTA_TIME_DECAY_TOTAL_PURCHASE_REVENUE
        , SUM(CREDIT_TIME_DECAY * USER_D7_PURCHASE_REVENUE) AS MTA_TIME_DECAY_D7_PURCHASE_REVENUE
        , SUM(CREDIT_TIME_DECAY * USER_D30_PURCHASE_REVENUE) AS MTA_TIME_DECAY_D30_PURCHASE_REVENUE

        -- =============================================
        -- AD REVENUE BY MODEL (Time-Decay only for brevity)
        -- =============================================
        , SUM(CREDIT_TIME_DECAY * USER_TOTAL_AD_REVENUE) AS MTA_TIME_DECAY_TOTAL_AD_REVENUE
        , SUM(CREDIT_TIME_DECAY * USER_D7_AD_REVENUE) AS MTA_TIME_DECAY_D7_AD_REVENUE
        , SUM(CREDIT_TIME_DECAY * USER_D30_AD_REVENUE) AS MTA_TIME_DECAY_D30_AD_REVENUE

        -- =============================================
        -- PAYERS BY MODEL
        -- =============================================
        , SUM(CREDIT_LAST_TOUCH * USER_IS_PAYER) AS MTA_LAST_TOUCH_TOTAL_PAYERS
        , SUM(CREDIT_FIRST_TOUCH * USER_IS_PAYER) AS MTA_FIRST_TOUCH_TOTAL_PAYERS
        , SUM(CREDIT_LINEAR * USER_IS_PAYER) AS MTA_LINEAR_TOTAL_PAYERS
        , SUM(CREDIT_TIME_DECAY * USER_IS_PAYER) AS MTA_TIME_DECAY_TOTAL_PAYERS
        , SUM(CREDIT_POSITION_BASED * USER_IS_PAYER) AS MTA_POSITION_BASED_TOTAL_PAYERS

        , SUM(CREDIT_TIME_DECAY * USER_IS_D7_PAYER) AS MTA_TIME_DECAY_D7_PAYERS
        , SUM(CREDIT_TIME_DECAY * USER_IS_D30_PAYER) AS MTA_TIME_DECAY_D30_PAYERS

        -- =============================================
        -- RETENTION BY MODEL
        -- =============================================
        , SUM(CREDIT_LAST_TOUCH * USER_D1_RETAINED) AS MTA_LAST_TOUCH_D1_RETAINED
        , SUM(CREDIT_FIRST_TOUCH * USER_D1_RETAINED) AS MTA_FIRST_TOUCH_D1_RETAINED
        , SUM(CREDIT_LINEAR * USER_D1_RETAINED) AS MTA_LINEAR_D1_RETAINED
        , SUM(CREDIT_TIME_DECAY * USER_D1_RETAINED) AS MTA_TIME_DECAY_D1_RETAINED
        , SUM(CREDIT_POSITION_BASED * USER_D1_RETAINED) AS MTA_POSITION_BASED_D1_RETAINED

        , SUM(CREDIT_LAST_TOUCH * USER_D7_RETAINED) AS MTA_LAST_TOUCH_D7_RETAINED
        , SUM(CREDIT_FIRST_TOUCH * USER_D7_RETAINED) AS MTA_FIRST_TOUCH_D7_RETAINED
        , SUM(CREDIT_LINEAR * USER_D7_RETAINED) AS MTA_LINEAR_D7_RETAINED
        , SUM(CREDIT_TIME_DECAY * USER_D7_RETAINED) AS MTA_TIME_DECAY_D7_RETAINED
        , SUM(CREDIT_POSITION_BASED * USER_D7_RETAINED) AS MTA_POSITION_BASED_D7_RETAINED

        , SUM(CREDIT_LAST_TOUCH * USER_D30_RETAINED) AS MTA_LAST_TOUCH_D30_RETAINED
        , SUM(CREDIT_FIRST_TOUCH * USER_D30_RETAINED) AS MTA_FIRST_TOUCH_D30_RETAINED
        , SUM(CREDIT_LINEAR * USER_D30_RETAINED) AS MTA_LINEAR_D30_RETAINED
        , SUM(CREDIT_TIME_DECAY * USER_D30_RETAINED) AS MTA_TIME_DECAY_D30_RETAINED
        , SUM(CREDIT_POSITION_BASED * USER_D30_RETAINED) AS MTA_POSITION_BASED_D30_RETAINED

        -- Maturity (Time-Decay only, same for all models)
        , SUM(CREDIT_TIME_DECAY * USER_D1_MATURED) AS MTA_D1_MATURED
        , SUM(CREDIT_TIME_DECAY * USER_D7_MATURED) AS MTA_D7_MATURED
        , SUM(CREDIT_TIME_DECAY * USER_D30_MATURED) AS MTA_D30_MATURED

    FROM touchpoints_with_metrics
    WHERE INSTALL_DATE IS NOT NULL
    GROUP BY 1, 2, 3, 4
)

-- =============================================
-- COMBINE ALL DATA SOURCES
-- Join on AD_PARTNER + CAMPAIGN_NAME + PLATFORM + DATE
-- =============================================
, combined AS (
    SELECT
        COALESCE(s.DATE, a.DATE, m.DATE) AS DATE
        , COALESCE(s.AD_PARTNER, a.AD_PARTNER, m.AD_PARTNER) AS AD_PARTNER
        , COALESCE(s.CAMPAIGN_NAME, a.CAMPAIGN_NAME, m.CAMPAIGN_NAME) AS CAMPAIGN_NAME
        , COALESCE(s.PLATFORM, a.PLATFORM, m.PLATFORM) AS PLATFORM

        -- Spend metrics
        , COALESCE(s.COST, 0) AS COST
        , COALESCE(s.CLICKS, 0) AS CLICKS
        , COALESCE(s.IMPRESSIONS, 0) AS IMPRESSIONS
        , COALESCE(s.ADJUST_NETWORK_INSTALLS, 0) AS ADJUST_NETWORK_INSTALLS

        -- Adjust attribution metrics
        , COALESCE(a.ADJUST_INSTALLS, 0) AS ADJUST_INSTALLS
        , COALESCE(a.ADJUST_TOTAL_REVENUE, 0) AS ADJUST_TOTAL_REVENUE
        , COALESCE(a.ADJUST_D7_REVENUE, 0) AS ADJUST_D7_REVENUE
        , COALESCE(a.ADJUST_D30_REVENUE, 0) AS ADJUST_D30_REVENUE
        , COALESCE(a.ADJUST_TOTAL_PURCHASE_REVENUE, 0) AS ADJUST_TOTAL_PURCHASE_REVENUE
        , COALESCE(a.ADJUST_D7_PURCHASE_REVENUE, 0) AS ADJUST_D7_PURCHASE_REVENUE
        , COALESCE(a.ADJUST_D30_PURCHASE_REVENUE, 0) AS ADJUST_D30_PURCHASE_REVENUE
        , COALESCE(a.ADJUST_TOTAL_AD_REVENUE, 0) AS ADJUST_TOTAL_AD_REVENUE
        , COALESCE(a.ADJUST_D7_AD_REVENUE, 0) AS ADJUST_D7_AD_REVENUE
        , COALESCE(a.ADJUST_D30_AD_REVENUE, 0) AS ADJUST_D30_AD_REVENUE
        , COALESCE(a.ADJUST_TOTAL_PAYERS, 0) AS ADJUST_TOTAL_PAYERS
        , COALESCE(a.ADJUST_D7_PAYERS, 0) AS ADJUST_D7_PAYERS
        , COALESCE(a.ADJUST_D30_PAYERS, 0) AS ADJUST_D30_PAYERS
        , COALESCE(a.ADJUST_D1_RETAINED, 0) AS ADJUST_D1_RETAINED
        , COALESCE(a.ADJUST_D7_RETAINED, 0) AS ADJUST_D7_RETAINED
        , COALESCE(a.ADJUST_D30_RETAINED, 0) AS ADJUST_D30_RETAINED
        , COALESCE(a.ADJUST_D1_MATURED, 0) AS ADJUST_D1_MATURED
        , COALESCE(a.ADJUST_D7_MATURED, 0) AS ADJUST_D7_MATURED
        , COALESCE(a.ADJUST_D30_MATURED, 0) AS ADJUST_D30_MATURED

        -- MTA Install metrics
        , COALESCE(m.MTA_LAST_TOUCH_INSTALLS, 0) AS MTA_LAST_TOUCH_INSTALLS
        , COALESCE(m.MTA_FIRST_TOUCH_INSTALLS, 0) AS MTA_FIRST_TOUCH_INSTALLS
        , COALESCE(m.MTA_LINEAR_INSTALLS, 0) AS MTA_LINEAR_INSTALLS
        , COALESCE(m.MTA_TIME_DECAY_INSTALLS, 0) AS MTA_TIME_DECAY_INSTALLS
        , COALESCE(m.MTA_POSITION_BASED_INSTALLS, 0) AS MTA_POSITION_BASED_INSTALLS

        -- MTA Total Revenue
        , COALESCE(m.MTA_LAST_TOUCH_TOTAL_REVENUE, 0) AS MTA_LAST_TOUCH_TOTAL_REVENUE
        , COALESCE(m.MTA_FIRST_TOUCH_TOTAL_REVENUE, 0) AS MTA_FIRST_TOUCH_TOTAL_REVENUE
        , COALESCE(m.MTA_LINEAR_TOTAL_REVENUE, 0) AS MTA_LINEAR_TOTAL_REVENUE
        , COALESCE(m.MTA_TIME_DECAY_TOTAL_REVENUE, 0) AS MTA_TIME_DECAY_TOTAL_REVENUE
        , COALESCE(m.MTA_POSITION_BASED_TOTAL_REVENUE, 0) AS MTA_POSITION_BASED_TOTAL_REVENUE

        -- MTA D7 Revenue
        , COALESCE(m.MTA_LAST_TOUCH_D7_REVENUE, 0) AS MTA_LAST_TOUCH_D7_REVENUE
        , COALESCE(m.MTA_FIRST_TOUCH_D7_REVENUE, 0) AS MTA_FIRST_TOUCH_D7_REVENUE
        , COALESCE(m.MTA_LINEAR_D7_REVENUE, 0) AS MTA_LINEAR_D7_REVENUE
        , COALESCE(m.MTA_TIME_DECAY_D7_REVENUE, 0) AS MTA_TIME_DECAY_D7_REVENUE
        , COALESCE(m.MTA_POSITION_BASED_D7_REVENUE, 0) AS MTA_POSITION_BASED_D7_REVENUE

        -- MTA D30 Revenue
        , COALESCE(m.MTA_LAST_TOUCH_D30_REVENUE, 0) AS MTA_LAST_TOUCH_D30_REVENUE
        , COALESCE(m.MTA_FIRST_TOUCH_D30_REVENUE, 0) AS MTA_FIRST_TOUCH_D30_REVENUE
        , COALESCE(m.MTA_LINEAR_D30_REVENUE, 0) AS MTA_LINEAR_D30_REVENUE
        , COALESCE(m.MTA_TIME_DECAY_D30_REVENUE, 0) AS MTA_TIME_DECAY_D30_REVENUE
        , COALESCE(m.MTA_POSITION_BASED_D30_REVENUE, 0) AS MTA_POSITION_BASED_D30_REVENUE

        -- MTA Purchase/Ad Revenue (Time-Decay)
        , COALESCE(m.MTA_TIME_DECAY_TOTAL_PURCHASE_REVENUE, 0) AS MTA_TIME_DECAY_TOTAL_PURCHASE_REVENUE
        , COALESCE(m.MTA_TIME_DECAY_D7_PURCHASE_REVENUE, 0) AS MTA_TIME_DECAY_D7_PURCHASE_REVENUE
        , COALESCE(m.MTA_TIME_DECAY_D30_PURCHASE_REVENUE, 0) AS MTA_TIME_DECAY_D30_PURCHASE_REVENUE
        , COALESCE(m.MTA_TIME_DECAY_TOTAL_AD_REVENUE, 0) AS MTA_TIME_DECAY_TOTAL_AD_REVENUE
        , COALESCE(m.MTA_TIME_DECAY_D7_AD_REVENUE, 0) AS MTA_TIME_DECAY_D7_AD_REVENUE
        , COALESCE(m.MTA_TIME_DECAY_D30_AD_REVENUE, 0) AS MTA_TIME_DECAY_D30_AD_REVENUE

        -- MTA Payers
        , COALESCE(m.MTA_LAST_TOUCH_TOTAL_PAYERS, 0) AS MTA_LAST_TOUCH_TOTAL_PAYERS
        , COALESCE(m.MTA_FIRST_TOUCH_TOTAL_PAYERS, 0) AS MTA_FIRST_TOUCH_TOTAL_PAYERS
        , COALESCE(m.MTA_LINEAR_TOTAL_PAYERS, 0) AS MTA_LINEAR_TOTAL_PAYERS
        , COALESCE(m.MTA_TIME_DECAY_TOTAL_PAYERS, 0) AS MTA_TIME_DECAY_TOTAL_PAYERS
        , COALESCE(m.MTA_POSITION_BASED_TOTAL_PAYERS, 0) AS MTA_POSITION_BASED_TOTAL_PAYERS
        , COALESCE(m.MTA_TIME_DECAY_D7_PAYERS, 0) AS MTA_TIME_DECAY_D7_PAYERS
        , COALESCE(m.MTA_TIME_DECAY_D30_PAYERS, 0) AS MTA_TIME_DECAY_D30_PAYERS

        -- MTA Retention
        , COALESCE(m.MTA_LAST_TOUCH_D1_RETAINED, 0) AS MTA_LAST_TOUCH_D1_RETAINED
        , COALESCE(m.MTA_FIRST_TOUCH_D1_RETAINED, 0) AS MTA_FIRST_TOUCH_D1_RETAINED
        , COALESCE(m.MTA_LINEAR_D1_RETAINED, 0) AS MTA_LINEAR_D1_RETAINED
        , COALESCE(m.MTA_TIME_DECAY_D1_RETAINED, 0) AS MTA_TIME_DECAY_D1_RETAINED
        , COALESCE(m.MTA_POSITION_BASED_D1_RETAINED, 0) AS MTA_POSITION_BASED_D1_RETAINED

        , COALESCE(m.MTA_LAST_TOUCH_D7_RETAINED, 0) AS MTA_LAST_TOUCH_D7_RETAINED
        , COALESCE(m.MTA_FIRST_TOUCH_D7_RETAINED, 0) AS MTA_FIRST_TOUCH_D7_RETAINED
        , COALESCE(m.MTA_LINEAR_D7_RETAINED, 0) AS MTA_LINEAR_D7_RETAINED
        , COALESCE(m.MTA_TIME_DECAY_D7_RETAINED, 0) AS MTA_TIME_DECAY_D7_RETAINED
        , COALESCE(m.MTA_POSITION_BASED_D7_RETAINED, 0) AS MTA_POSITION_BASED_D7_RETAINED

        , COALESCE(m.MTA_LAST_TOUCH_D30_RETAINED, 0) AS MTA_LAST_TOUCH_D30_RETAINED
        , COALESCE(m.MTA_FIRST_TOUCH_D30_RETAINED, 0) AS MTA_FIRST_TOUCH_D30_RETAINED
        , COALESCE(m.MTA_LINEAR_D30_RETAINED, 0) AS MTA_LINEAR_D30_RETAINED
        , COALESCE(m.MTA_TIME_DECAY_D30_RETAINED, 0) AS MTA_TIME_DECAY_D30_RETAINED
        , COALESCE(m.MTA_POSITION_BASED_D30_RETAINED, 0) AS MTA_POSITION_BASED_D30_RETAINED

        , COALESCE(m.MTA_D1_MATURED, 0) AS MTA_D1_MATURED
        , COALESCE(m.MTA_D7_MATURED, 0) AS MTA_D7_MATURED
        , COALESCE(m.MTA_D30_MATURED, 0) AS MTA_D30_MATURED

    FROM spend_data s
    FULL OUTER JOIN adjust_metrics a
        ON s.DATE = a.DATE
        AND LOWER(s.AD_PARTNER) = LOWER(a.AD_PARTNER)
        AND LOWER(s.CAMPAIGN_NAME) = LOWER(a.CAMPAIGN_NAME)
        AND LOWER(s.PLATFORM) = LOWER(a.PLATFORM)
    FULL OUTER JOIN mta_metrics m
        ON COALESCE(s.DATE, a.DATE) = m.DATE
        AND LOWER(COALESCE(s.AD_PARTNER, a.AD_PARTNER)) = LOWER(m.AD_PARTNER)
        AND LOWER(COALESCE(s.CAMPAIGN_NAME, a.CAMPAIGN_NAME)) = LOWER(m.CAMPAIGN_NAME)
        AND LOWER(COALESCE(s.PLATFORM, a.PLATFORM)) = LOWER(m.PLATFORM)
)

-- =============================================
-- FINAL OUTPUT WITH CALCULATED METRICS
-- =============================================
SELECT
    DATE
    , AD_PARTNER
    , CAMPAIGN_NAME
    , PLATFORM

    -- =============================================
    -- SPEND METRICS
    -- =============================================
    , COST
    , CLICKS
    , IMPRESSIONS
    , ADJUST_NETWORK_INSTALLS

    -- =============================================
    -- FUNNEL EFFICIENCY (based on Adjust network data)
    -- =============================================
    , CASE WHEN IMPRESSIONS > 0 THEN (COST / IMPRESSIONS) * 1000 ELSE NULL END AS CPM
    , CASE WHEN IMPRESSIONS > 0 THEN CLICKS / IMPRESSIONS ELSE NULL END AS CTR
    , CASE WHEN IMPRESSIONS > 0 THEN (ADJUST_NETWORK_INSTALLS / IMPRESSIONS) * 1000 ELSE NULL END AS IPM

    -- =============================================
    -- INSTALLS BY ATTRIBUTION MODEL
    -- =============================================
    , ADJUST_INSTALLS
    , MTA_LAST_TOUCH_INSTALLS
    , MTA_FIRST_TOUCH_INSTALLS
    , MTA_LINEAR_INSTALLS
    , MTA_TIME_DECAY_INSTALLS
    , MTA_POSITION_BASED_INSTALLS

    -- =============================================
    -- CPI BY ATTRIBUTION MODEL
    -- =============================================
    , CASE WHEN ADJUST_INSTALLS > 0 THEN COST / ADJUST_INSTALLS ELSE NULL END AS ADJUST_CPI
    , CASE WHEN MTA_LAST_TOUCH_INSTALLS > 0 THEN COST / MTA_LAST_TOUCH_INSTALLS ELSE NULL END AS MTA_LAST_TOUCH_CPI
    , CASE WHEN MTA_FIRST_TOUCH_INSTALLS > 0 THEN COST / MTA_FIRST_TOUCH_INSTALLS ELSE NULL END AS MTA_FIRST_TOUCH_CPI
    , CASE WHEN MTA_LINEAR_INSTALLS > 0 THEN COST / MTA_LINEAR_INSTALLS ELSE NULL END AS MTA_LINEAR_CPI
    , CASE WHEN MTA_TIME_DECAY_INSTALLS > 0 THEN COST / MTA_TIME_DECAY_INSTALLS ELSE NULL END AS MTA_TIME_DECAY_CPI
    , CASE WHEN MTA_POSITION_BASED_INSTALLS > 0 THEN COST / MTA_POSITION_BASED_INSTALLS ELSE NULL END AS MTA_POSITION_BASED_CPI

    -- =============================================
    -- TOTAL REVENUE BY ATTRIBUTION MODEL
    -- =============================================
    , ADJUST_TOTAL_REVENUE
    , MTA_LAST_TOUCH_TOTAL_REVENUE
    , MTA_FIRST_TOUCH_TOTAL_REVENUE
    , MTA_LINEAR_TOTAL_REVENUE
    , MTA_TIME_DECAY_TOTAL_REVENUE
    , MTA_POSITION_BASED_TOTAL_REVENUE

    -- =============================================
    -- D7 REVENUE BY ATTRIBUTION MODEL
    -- =============================================
    , ADJUST_D7_REVENUE
    , MTA_LAST_TOUCH_D7_REVENUE
    , MTA_FIRST_TOUCH_D7_REVENUE
    , MTA_LINEAR_D7_REVENUE
    , MTA_TIME_DECAY_D7_REVENUE
    , MTA_POSITION_BASED_D7_REVENUE

    -- =============================================
    -- D30 REVENUE BY ATTRIBUTION MODEL
    -- =============================================
    , ADJUST_D30_REVENUE
    , MTA_LAST_TOUCH_D30_REVENUE
    , MTA_FIRST_TOUCH_D30_REVENUE
    , MTA_LINEAR_D30_REVENUE
    , MTA_TIME_DECAY_D30_REVENUE
    , MTA_POSITION_BASED_D30_REVENUE

    -- =============================================
    -- PURCHASE/AD REVENUE SPLIT (Time-Decay)
    -- =============================================
    , ADJUST_TOTAL_PURCHASE_REVENUE
    , MTA_TIME_DECAY_TOTAL_PURCHASE_REVENUE
    , ADJUST_D7_PURCHASE_REVENUE
    , MTA_TIME_DECAY_D7_PURCHASE_REVENUE
    , ADJUST_D30_PURCHASE_REVENUE
    , MTA_TIME_DECAY_D30_PURCHASE_REVENUE
    , ADJUST_TOTAL_AD_REVENUE
    , MTA_TIME_DECAY_TOTAL_AD_REVENUE
    , ADJUST_D7_AD_REVENUE
    , MTA_TIME_DECAY_D7_AD_REVENUE
    , ADJUST_D30_AD_REVENUE
    , MTA_TIME_DECAY_D30_AD_REVENUE

    -- =============================================
    -- D7 ROAS BY ATTRIBUTION MODEL
    -- =============================================
    , CASE WHEN COST > 0 THEN ADJUST_D7_REVENUE / COST ELSE NULL END AS ADJUST_D7_ROAS
    , CASE WHEN COST > 0 THEN MTA_LAST_TOUCH_D7_REVENUE / COST ELSE NULL END AS MTA_LAST_TOUCH_D7_ROAS
    , CASE WHEN COST > 0 THEN MTA_FIRST_TOUCH_D7_REVENUE / COST ELSE NULL END AS MTA_FIRST_TOUCH_D7_ROAS
    , CASE WHEN COST > 0 THEN MTA_LINEAR_D7_REVENUE / COST ELSE NULL END AS MTA_LINEAR_D7_ROAS
    , CASE WHEN COST > 0 THEN MTA_TIME_DECAY_D7_REVENUE / COST ELSE NULL END AS MTA_TIME_DECAY_D7_ROAS
    , CASE WHEN COST > 0 THEN MTA_POSITION_BASED_D7_REVENUE / COST ELSE NULL END AS MTA_POSITION_BASED_D7_ROAS

    -- =============================================
    -- D30 ROAS BY ATTRIBUTION MODEL
    -- =============================================
    , CASE WHEN COST > 0 THEN ADJUST_D30_REVENUE / COST ELSE NULL END AS ADJUST_D30_ROAS
    , CASE WHEN COST > 0 THEN MTA_LAST_TOUCH_D30_REVENUE / COST ELSE NULL END AS MTA_LAST_TOUCH_D30_ROAS
    , CASE WHEN COST > 0 THEN MTA_FIRST_TOUCH_D30_REVENUE / COST ELSE NULL END AS MTA_FIRST_TOUCH_D30_ROAS
    , CASE WHEN COST > 0 THEN MTA_LINEAR_D30_REVENUE / COST ELSE NULL END AS MTA_LINEAR_D30_ROAS
    , CASE WHEN COST > 0 THEN MTA_TIME_DECAY_D30_REVENUE / COST ELSE NULL END AS MTA_TIME_DECAY_D30_ROAS
    , CASE WHEN COST > 0 THEN MTA_POSITION_BASED_D30_REVENUE / COST ELSE NULL END AS MTA_POSITION_BASED_D30_ROAS

    -- =============================================
    -- TOTAL ROAS BY ATTRIBUTION MODEL
    -- =============================================
    , CASE WHEN COST > 0 THEN ADJUST_TOTAL_REVENUE / COST ELSE NULL END AS ADJUST_TOTAL_ROAS
    , CASE WHEN COST > 0 THEN MTA_LAST_TOUCH_TOTAL_REVENUE / COST ELSE NULL END AS MTA_LAST_TOUCH_TOTAL_ROAS
    , CASE WHEN COST > 0 THEN MTA_FIRST_TOUCH_TOTAL_REVENUE / COST ELSE NULL END AS MTA_FIRST_TOUCH_TOTAL_ROAS
    , CASE WHEN COST > 0 THEN MTA_LINEAR_TOTAL_REVENUE / COST ELSE NULL END AS MTA_LINEAR_TOTAL_ROAS
    , CASE WHEN COST > 0 THEN MTA_TIME_DECAY_TOTAL_REVENUE / COST ELSE NULL END AS MTA_TIME_DECAY_TOTAL_ROAS
    , CASE WHEN COST > 0 THEN MTA_POSITION_BASED_TOTAL_REVENUE / COST ELSE NULL END AS MTA_POSITION_BASED_TOTAL_ROAS

    -- =============================================
    -- D7 ARPI BY ATTRIBUTION MODEL
    -- =============================================
    , CASE WHEN ADJUST_INSTALLS > 0 THEN ADJUST_D7_REVENUE / ADJUST_INSTALLS ELSE NULL END AS ADJUST_D7_ARPI
    , CASE WHEN MTA_TIME_DECAY_INSTALLS > 0 THEN MTA_TIME_DECAY_D7_REVENUE / MTA_TIME_DECAY_INSTALLS ELSE NULL END AS MTA_TIME_DECAY_D7_ARPI

    -- =============================================
    -- TOTAL PAYERS BY ATTRIBUTION MODEL
    -- =============================================
    , ADJUST_TOTAL_PAYERS
    , MTA_LAST_TOUCH_TOTAL_PAYERS
    , MTA_FIRST_TOUCH_TOTAL_PAYERS
    , MTA_LINEAR_TOTAL_PAYERS
    , MTA_TIME_DECAY_TOTAL_PAYERS
    , MTA_POSITION_BASED_TOTAL_PAYERS
    , ADJUST_D7_PAYERS
    , MTA_TIME_DECAY_D7_PAYERS
    , ADJUST_D30_PAYERS
    , MTA_TIME_DECAY_D30_PAYERS

    -- =============================================
    -- PAYER CONVERSION RATE BY ATTRIBUTION MODEL
    -- =============================================
    , CASE WHEN ADJUST_INSTALLS > 0 THEN ADJUST_TOTAL_PAYERS / ADJUST_INSTALLS ELSE NULL END AS ADJUST_PAYER_CVR
    , CASE WHEN MTA_LAST_TOUCH_INSTALLS > 0 THEN MTA_LAST_TOUCH_TOTAL_PAYERS / MTA_LAST_TOUCH_INSTALLS ELSE NULL END AS MTA_LAST_TOUCH_PAYER_CVR
    , CASE WHEN MTA_FIRST_TOUCH_INSTALLS > 0 THEN MTA_FIRST_TOUCH_TOTAL_PAYERS / MTA_FIRST_TOUCH_INSTALLS ELSE NULL END AS MTA_FIRST_TOUCH_PAYER_CVR
    , CASE WHEN MTA_LINEAR_INSTALLS > 0 THEN MTA_LINEAR_TOTAL_PAYERS / MTA_LINEAR_INSTALLS ELSE NULL END AS MTA_LINEAR_PAYER_CVR
    , CASE WHEN MTA_TIME_DECAY_INSTALLS > 0 THEN MTA_TIME_DECAY_TOTAL_PAYERS / MTA_TIME_DECAY_INSTALLS ELSE NULL END AS MTA_TIME_DECAY_PAYER_CVR
    , CASE WHEN MTA_POSITION_BASED_INSTALLS > 0 THEN MTA_POSITION_BASED_TOTAL_PAYERS / MTA_POSITION_BASED_INSTALLS ELSE NULL END AS MTA_POSITION_BASED_PAYER_CVR

    -- =============================================
    -- D1 RETENTION BY ATTRIBUTION MODEL
    -- =============================================
    , ADJUST_D1_RETAINED
    , MTA_LAST_TOUCH_D1_RETAINED
    , MTA_FIRST_TOUCH_D1_RETAINED
    , MTA_LINEAR_D1_RETAINED
    , MTA_TIME_DECAY_D1_RETAINED
    , MTA_POSITION_BASED_D1_RETAINED
    , ADJUST_D1_MATURED
    , MTA_D1_MATURED

    , CASE WHEN ADJUST_D1_MATURED > 0 THEN ADJUST_D1_RETAINED / ADJUST_D1_MATURED ELSE NULL END AS ADJUST_D1_RETENTION
    , CASE WHEN MTA_D1_MATURED > 0 THEN MTA_LAST_TOUCH_D1_RETAINED / MTA_D1_MATURED ELSE NULL END AS MTA_LAST_TOUCH_D1_RETENTION
    , CASE WHEN MTA_D1_MATURED > 0 THEN MTA_FIRST_TOUCH_D1_RETAINED / MTA_D1_MATURED ELSE NULL END AS MTA_FIRST_TOUCH_D1_RETENTION
    , CASE WHEN MTA_D1_MATURED > 0 THEN MTA_LINEAR_D1_RETAINED / MTA_D1_MATURED ELSE NULL END AS MTA_LINEAR_D1_RETENTION
    , CASE WHEN MTA_D1_MATURED > 0 THEN MTA_TIME_DECAY_D1_RETAINED / MTA_D1_MATURED ELSE NULL END AS MTA_TIME_DECAY_D1_RETENTION
    , CASE WHEN MTA_D1_MATURED > 0 THEN MTA_POSITION_BASED_D1_RETAINED / MTA_D1_MATURED ELSE NULL END AS MTA_POSITION_BASED_D1_RETENTION

    -- =============================================
    -- D7 RETENTION BY ATTRIBUTION MODEL
    -- =============================================
    , ADJUST_D7_RETAINED
    , MTA_LAST_TOUCH_D7_RETAINED
    , MTA_FIRST_TOUCH_D7_RETAINED
    , MTA_LINEAR_D7_RETAINED
    , MTA_TIME_DECAY_D7_RETAINED
    , MTA_POSITION_BASED_D7_RETAINED
    , ADJUST_D7_MATURED
    , MTA_D7_MATURED

    , CASE WHEN ADJUST_D7_MATURED > 0 THEN ADJUST_D7_RETAINED / ADJUST_D7_MATURED ELSE NULL END AS ADJUST_D7_RETENTION
    , CASE WHEN MTA_D7_MATURED > 0 THEN MTA_LAST_TOUCH_D7_RETAINED / MTA_D7_MATURED ELSE NULL END AS MTA_LAST_TOUCH_D7_RETENTION
    , CASE WHEN MTA_D7_MATURED > 0 THEN MTA_FIRST_TOUCH_D7_RETAINED / MTA_D7_MATURED ELSE NULL END AS MTA_FIRST_TOUCH_D7_RETENTION
    , CASE WHEN MTA_D7_MATURED > 0 THEN MTA_LINEAR_D7_RETAINED / MTA_D7_MATURED ELSE NULL END AS MTA_LINEAR_D7_RETENTION
    , CASE WHEN MTA_D7_MATURED > 0 THEN MTA_TIME_DECAY_D7_RETAINED / MTA_D7_MATURED ELSE NULL END AS MTA_TIME_DECAY_D7_RETENTION
    , CASE WHEN MTA_D7_MATURED > 0 THEN MTA_POSITION_BASED_D7_RETAINED / MTA_D7_MATURED ELSE NULL END AS MTA_POSITION_BASED_D7_RETENTION

    -- =============================================
    -- D30 RETENTION BY ATTRIBUTION MODEL
    -- =============================================
    , ADJUST_D30_RETAINED
    , MTA_LAST_TOUCH_D30_RETAINED
    , MTA_FIRST_TOUCH_D30_RETAINED
    , MTA_LINEAR_D30_RETAINED
    , MTA_TIME_DECAY_D30_RETAINED
    , MTA_POSITION_BASED_D30_RETAINED
    , ADJUST_D30_MATURED
    , MTA_D30_MATURED

    , CASE WHEN ADJUST_D30_MATURED > 0 THEN ADJUST_D30_RETAINED / ADJUST_D30_MATURED ELSE NULL END AS ADJUST_D30_RETENTION
    , CASE WHEN MTA_D30_MATURED > 0 THEN MTA_LAST_TOUCH_D30_RETAINED / MTA_D30_MATURED ELSE NULL END AS MTA_LAST_TOUCH_D30_RETENTION
    , CASE WHEN MTA_D30_MATURED > 0 THEN MTA_FIRST_TOUCH_D30_RETAINED / MTA_D30_MATURED ELSE NULL END AS MTA_FIRST_TOUCH_D30_RETENTION
    , CASE WHEN MTA_D30_MATURED > 0 THEN MTA_LINEAR_D30_RETAINED / MTA_D30_MATURED ELSE NULL END AS MTA_LINEAR_D30_RETENTION
    , CASE WHEN MTA_D30_MATURED > 0 THEN MTA_TIME_DECAY_D30_RETAINED / MTA_D30_MATURED ELSE NULL END AS MTA_TIME_DECAY_D30_RETENTION
    , CASE WHEN MTA_D30_MATURED > 0 THEN MTA_POSITION_BASED_D30_RETAINED / MTA_D30_MATURED ELSE NULL END AS MTA_POSITION_BASED_D30_RETENTION

    -- =============================================
    -- MTA COVERAGE (fraction of installs with MTA data)
    -- Values near 0 for Meta/Google indicate SAN data limitations
    -- =============================================
    , CASE WHEN ADJUST_INSTALLS > 0
        THEN MTA_TIME_DECAY_INSTALLS / ADJUST_INSTALLS
        ELSE NULL
      END AS MTA_COVERAGE_RATE

FROM combined
WHERE DATE IS NOT NULL
