-- ============================================================================
-- LIMITATION NOTICE (documented Phase 3, 2026-02)
--
-- This model is part of the Multi-Touch Attribution (MTA) pipeline.
-- Phase 2 audit (Feb 2026) found that MTA has structural coverage limitations:
--   - Android: 0% device match rate (Amplitude SDK uses random UUID, not GPS_ADID)
--   - iOS IDFA: 7.37% availability (Apple ATT framework)
--   - SANs (Meta, Google, Apple, TikTok): 0% touchpoint data (never shared)
--
-- This model is PRESERVED for iOS tactical analysis only.
-- For strategic budget allocation, use MMM models in marts/mmm/.
--
-- To fix Android: Amplitude SDK must be configured with useAdvertisingIdForDeviceId()
-- See: .planning/phases/03-device-id-normalization-fix/mta-limitations.md
-- ============================================================================

-- mta__campaign_ltv.sql
-- MTA-Attributed LTV per Campaign
-- Applies fractional MTA credit to device-level LTV windows
-- Compare LTV across 6 attribution models × 6 LTV windows
--
-- Grain: One row per AD_PARTNER + CAMPAIGN_ID + PLATFORM + DATE

{{
    config(
        materialized='incremental',
        unique_key=['AD_PARTNER', 'CAMPAIGN_ID', 'PLATFORM', 'DATE'],
        incremental_strategy='merge',
        on_schema_change='append_new_columns',
        tags=['mta', 'attribution', 'ltv', 'mart']
    )
}}

-- Get touchpoint credits
WITH touchpoint_credits AS (
    SELECT tc.DEVICE_ID
         , tc.PLATFORM
         , tc.AD_PARTNER
         , tc.NETWORK_NAME
         , tc.CAMPAIGN_NAME
         , tc.CAMPAIGN_ID
         , CAST(tc.INSTALL_TIMESTAMP AS DATE) AS INSTALL_DATE
         , tc.CREDIT_LAST_TOUCH
         , tc.CREDIT_FIRST_TOUCH
         , tc.CREDIT_LINEAR
         , tc.CREDIT_TIME_DECAY
         , tc.CREDIT_POSITION_BASED
         , tc.CREDIT_RECOMMENDED
    FROM {{ ref('int_mta__touchpoint_credit') }} tc
    {% if is_incremental() %}
        WHERE CAST(tc.INSTALL_TIMESTAMP AS DATE) >= DATEADD(day, -7, (SELECT MAX(DATE) FROM {{ this }}))
    {% endif %}
)

-- Get device-level LTV
, device_ltv AS (
    SELECT DEVICE_ID
         , PLATFORM
         , HAS_USER_MAPPING
         , D1_REVENUE
         , D7_REVENUE
         , D30_REVENUE
         , D180_REVENUE
         , D365_REVENUE
         , TOTAL_REVENUE
         , D1_MATURED
         , D7_MATURED
         , D30_MATURED
         , D180_MATURED
         , D365_MATURED
    FROM {{ ref('int_ltv__device_revenue') }}
)

-- Join touchpoints to device LTV
, touchpoints_with_ltv AS (
    SELECT tc.*
         , dl.HAS_USER_MAPPING
         , COALESCE(dl.D1_REVENUE, 0) AS DEVICE_D1_REVENUE
         , COALESCE(dl.D7_REVENUE, 0) AS DEVICE_D7_REVENUE
         , COALESCE(dl.D30_REVENUE, 0) AS DEVICE_D30_REVENUE
         , COALESCE(dl.D180_REVENUE, 0) AS DEVICE_D180_REVENUE
         , COALESCE(dl.D365_REVENUE, 0) AS DEVICE_D365_REVENUE
         , COALESCE(dl.TOTAL_REVENUE, 0) AS DEVICE_TOTAL_REVENUE
         , COALESCE(dl.D1_MATURED, 0) AS DEVICE_D1_MATURED
         , COALESCE(dl.D7_MATURED, 0) AS DEVICE_D7_MATURED
         , COALESCE(dl.D30_MATURED, 0) AS DEVICE_D30_MATURED
         , COALESCE(dl.D180_MATURED, 0) AS DEVICE_D180_MATURED
         , COALESCE(dl.D365_MATURED, 0) AS DEVICE_D365_MATURED
    FROM touchpoint_credits tc
    LEFT JOIN device_ltv dl
        ON tc.DEVICE_ID = dl.DEVICE_ID
        AND tc.PLATFORM = dl.PLATFORM
)

-- Aggregate by campaign and date
, campaign_aggregated AS (
    SELECT AD_PARTNER
         , NETWORK_NAME
         , CAMPAIGN_NAME
         , CAMPAIGN_ID
         , PLATFORM
         , INSTALL_DATE AS DATE

         -- =============================================
         -- INSTALL ATTRIBUTION BY MODEL
         -- =============================================
         , SUM(CREDIT_LAST_TOUCH) AS INSTALLS_LAST_TOUCH
         , SUM(CREDIT_FIRST_TOUCH) AS INSTALLS_FIRST_TOUCH
         , SUM(CREDIT_LINEAR) AS INSTALLS_LINEAR
         , SUM(CREDIT_TIME_DECAY) AS INSTALLS_TIME_DECAY
         , SUM(CREDIT_POSITION_BASED) AS INSTALLS_POSITION_BASED
         , SUM(CREDIT_RECOMMENDED) AS INSTALLS_RECOMMENDED

         -- =============================================
         -- D1 REVENUE ATTRIBUTION BY MODEL
         -- =============================================
         , SUM(CREDIT_LAST_TOUCH * DEVICE_D1_REVENUE) AS D1_REVENUE_LAST_TOUCH
         , SUM(CREDIT_FIRST_TOUCH * DEVICE_D1_REVENUE) AS D1_REVENUE_FIRST_TOUCH
         , SUM(CREDIT_LINEAR * DEVICE_D1_REVENUE) AS D1_REVENUE_LINEAR
         , SUM(CREDIT_TIME_DECAY * DEVICE_D1_REVENUE) AS D1_REVENUE_TIME_DECAY
         , SUM(CREDIT_POSITION_BASED * DEVICE_D1_REVENUE) AS D1_REVENUE_POSITION_BASED
         , SUM(CREDIT_RECOMMENDED * DEVICE_D1_REVENUE) AS D1_REVENUE_RECOMMENDED

         -- =============================================
         -- D7 REVENUE ATTRIBUTION BY MODEL
         -- =============================================
         , SUM(CREDIT_LAST_TOUCH * DEVICE_D7_REVENUE) AS D7_REVENUE_LAST_TOUCH
         , SUM(CREDIT_FIRST_TOUCH * DEVICE_D7_REVENUE) AS D7_REVENUE_FIRST_TOUCH
         , SUM(CREDIT_LINEAR * DEVICE_D7_REVENUE) AS D7_REVENUE_LINEAR
         , SUM(CREDIT_TIME_DECAY * DEVICE_D7_REVENUE) AS D7_REVENUE_TIME_DECAY
         , SUM(CREDIT_POSITION_BASED * DEVICE_D7_REVENUE) AS D7_REVENUE_POSITION_BASED
         , SUM(CREDIT_RECOMMENDED * DEVICE_D7_REVENUE) AS D7_REVENUE_RECOMMENDED

         -- =============================================
         -- D30 REVENUE ATTRIBUTION BY MODEL
         -- =============================================
         , SUM(CREDIT_LAST_TOUCH * DEVICE_D30_REVENUE) AS D30_REVENUE_LAST_TOUCH
         , SUM(CREDIT_FIRST_TOUCH * DEVICE_D30_REVENUE) AS D30_REVENUE_FIRST_TOUCH
         , SUM(CREDIT_LINEAR * DEVICE_D30_REVENUE) AS D30_REVENUE_LINEAR
         , SUM(CREDIT_TIME_DECAY * DEVICE_D30_REVENUE) AS D30_REVENUE_TIME_DECAY
         , SUM(CREDIT_POSITION_BASED * DEVICE_D30_REVENUE) AS D30_REVENUE_POSITION_BASED
         , SUM(CREDIT_RECOMMENDED * DEVICE_D30_REVENUE) AS D30_REVENUE_RECOMMENDED

         -- =============================================
         -- D180 REVENUE ATTRIBUTION BY MODEL
         -- =============================================
         , SUM(CREDIT_LAST_TOUCH * DEVICE_D180_REVENUE) AS D180_REVENUE_LAST_TOUCH
         , SUM(CREDIT_FIRST_TOUCH * DEVICE_D180_REVENUE) AS D180_REVENUE_FIRST_TOUCH
         , SUM(CREDIT_LINEAR * DEVICE_D180_REVENUE) AS D180_REVENUE_LINEAR
         , SUM(CREDIT_TIME_DECAY * DEVICE_D180_REVENUE) AS D180_REVENUE_TIME_DECAY
         , SUM(CREDIT_POSITION_BASED * DEVICE_D180_REVENUE) AS D180_REVENUE_POSITION_BASED
         , SUM(CREDIT_RECOMMENDED * DEVICE_D180_REVENUE) AS D180_REVENUE_RECOMMENDED

         -- =============================================
         -- D365 REVENUE ATTRIBUTION BY MODEL
         -- =============================================
         , SUM(CREDIT_LAST_TOUCH * DEVICE_D365_REVENUE) AS D365_REVENUE_LAST_TOUCH
         , SUM(CREDIT_FIRST_TOUCH * DEVICE_D365_REVENUE) AS D365_REVENUE_FIRST_TOUCH
         , SUM(CREDIT_LINEAR * DEVICE_D365_REVENUE) AS D365_REVENUE_LINEAR
         , SUM(CREDIT_TIME_DECAY * DEVICE_D365_REVENUE) AS D365_REVENUE_TIME_DECAY
         , SUM(CREDIT_POSITION_BASED * DEVICE_D365_REVENUE) AS D365_REVENUE_POSITION_BASED
         , SUM(CREDIT_RECOMMENDED * DEVICE_D365_REVENUE) AS D365_REVENUE_RECOMMENDED

         -- =============================================
         -- TOTAL REVENUE ATTRIBUTION BY MODEL
         -- =============================================
         , SUM(CREDIT_LAST_TOUCH * DEVICE_TOTAL_REVENUE) AS TOTAL_REVENUE_LAST_TOUCH
         , SUM(CREDIT_FIRST_TOUCH * DEVICE_TOTAL_REVENUE) AS TOTAL_REVENUE_FIRST_TOUCH
         , SUM(CREDIT_LINEAR * DEVICE_TOTAL_REVENUE) AS TOTAL_REVENUE_LINEAR
         , SUM(CREDIT_TIME_DECAY * DEVICE_TOTAL_REVENUE) AS TOTAL_REVENUE_TIME_DECAY
         , SUM(CREDIT_POSITION_BASED * DEVICE_TOTAL_REVENUE) AS TOTAL_REVENUE_POSITION_BASED
         , SUM(CREDIT_RECOMMENDED * DEVICE_TOTAL_REVENUE) AS TOTAL_REVENUE_RECOMMENDED

         -- =============================================
         -- COVERAGE METRICS
         -- =============================================
         , COUNT(DISTINCT DEVICE_ID) AS UNIQUE_DEVICES
         , COUNT(DISTINCT CASE WHEN HAS_USER_MAPPING THEN DEVICE_ID END) AS DEVICES_WITH_USER_MAPPING

         -- Matured device counts per window
         , SUM(DEVICE_D1_MATURED) AS D1_MATURED_DEVICES
         , SUM(DEVICE_D7_MATURED) AS D7_MATURED_DEVICES
         , SUM(DEVICE_D30_MATURED) AS D30_MATURED_DEVICES
         , SUM(DEVICE_D180_MATURED) AS D180_MATURED_DEVICES
         , SUM(DEVICE_D365_MATURED) AS D365_MATURED_DEVICES

    FROM touchpoints_with_ltv
    GROUP BY AD_PARTNER
           , NETWORK_NAME
           , CAMPAIGN_NAME
           , CAMPAIGN_ID
           , PLATFORM
           , INSTALL_DATE
)

-- Map spend partner names to canonical AD_PARTNER names
, partner_map AS (
    SELECT DISTINCT
        ADJUST_NETWORK_NAME AS PARTNER_NAME
        , AD_PARTNER
    FROM {{ ref('network_mapping') }}
    WHERE AD_PARTNER IS NOT NULL

    UNION

    SELECT DISTINCT
        SUPERMETRICS_PARTNER_NAME || ' (Ad Spend)' AS PARTNER_NAME
        , AD_PARTNER
    FROM {{ ref('network_mapping') }}
    WHERE AD_PARTNER IS NOT NULL
)

-- Join with spend data from Adjust API
, spend AS (
    SELECT COALESCE(pm.AD_PARTNER, s.PARTNER_NAME) AS AD_PARTNER
         , s.CAMPAIGN_ID_NETWORK AS CAMPAIGN_ID
         , s.PLATFORM
         , s.DATE
         , SUM(s.NETWORK_COST) AS COST
         , SUM(s.CLICKS) AS CLICKS
         , SUM(s.IMPRESSIONS) AS IMPRESSIONS
    FROM {{ ref('stg_adjust__report_daily') }} s
    LEFT JOIN partner_map pm ON s.PARTNER_NAME = pm.PARTNER_NAME
    WHERE TRY_TO_NUMBER(s.CAMPAIGN_ID_NETWORK) IS NOT NULL
    {% if is_incremental() %}
        AND s.DATE >= DATEADD(day, -7, (SELECT MAX(DATE) FROM {{ this }}))
    {% endif %}
    GROUP BY 1, 2, 3, 4
)

-- Final join with spend
, final AS (
    SELECT COALESCE(a.AD_PARTNER, s.AD_PARTNER) AS AD_PARTNER
         , a.NETWORK_NAME
         , a.CAMPAIGN_NAME
         , COALESCE(a.CAMPAIGN_ID, s.CAMPAIGN_ID) AS CAMPAIGN_ID
         , COALESCE(a.PLATFORM, s.PLATFORM) AS PLATFORM
         , COALESCE(a.DATE, s.DATE) AS DATE

         -- Spend metrics
         , COALESCE(s.COST, 0) AS COST
         , COALESCE(s.CLICKS, 0) AS CLICKS
         , COALESCE(s.IMPRESSIONS, 0) AS IMPRESSIONS

         -- Install metrics by model
         , COALESCE(a.INSTALLS_LAST_TOUCH, 0) AS INSTALLS_LAST_TOUCH
         , COALESCE(a.INSTALLS_FIRST_TOUCH, 0) AS INSTALLS_FIRST_TOUCH
         , COALESCE(a.INSTALLS_LINEAR, 0) AS INSTALLS_LINEAR
         , COALESCE(a.INSTALLS_TIME_DECAY, 0) AS INSTALLS_TIME_DECAY
         , COALESCE(a.INSTALLS_POSITION_BASED, 0) AS INSTALLS_POSITION_BASED
         , COALESCE(a.INSTALLS_RECOMMENDED, 0) AS INSTALLS_RECOMMENDED

         -- D1 Revenue by model
         , COALESCE(a.D1_REVENUE_LAST_TOUCH, 0) AS D1_REVENUE_LAST_TOUCH
         , COALESCE(a.D1_REVENUE_FIRST_TOUCH, 0) AS D1_REVENUE_FIRST_TOUCH
         , COALESCE(a.D1_REVENUE_LINEAR, 0) AS D1_REVENUE_LINEAR
         , COALESCE(a.D1_REVENUE_TIME_DECAY, 0) AS D1_REVENUE_TIME_DECAY
         , COALESCE(a.D1_REVENUE_POSITION_BASED, 0) AS D1_REVENUE_POSITION_BASED
         , COALESCE(a.D1_REVENUE_RECOMMENDED, 0) AS D1_REVENUE_RECOMMENDED

         -- D7 Revenue by model
         , COALESCE(a.D7_REVENUE_LAST_TOUCH, 0) AS D7_REVENUE_LAST_TOUCH
         , COALESCE(a.D7_REVENUE_FIRST_TOUCH, 0) AS D7_REVENUE_FIRST_TOUCH
         , COALESCE(a.D7_REVENUE_LINEAR, 0) AS D7_REVENUE_LINEAR
         , COALESCE(a.D7_REVENUE_TIME_DECAY, 0) AS D7_REVENUE_TIME_DECAY
         , COALESCE(a.D7_REVENUE_POSITION_BASED, 0) AS D7_REVENUE_POSITION_BASED
         , COALESCE(a.D7_REVENUE_RECOMMENDED, 0) AS D7_REVENUE_RECOMMENDED

         -- D30 Revenue by model
         , COALESCE(a.D30_REVENUE_LAST_TOUCH, 0) AS D30_REVENUE_LAST_TOUCH
         , COALESCE(a.D30_REVENUE_FIRST_TOUCH, 0) AS D30_REVENUE_FIRST_TOUCH
         , COALESCE(a.D30_REVENUE_LINEAR, 0) AS D30_REVENUE_LINEAR
         , COALESCE(a.D30_REVENUE_TIME_DECAY, 0) AS D30_REVENUE_TIME_DECAY
         , COALESCE(a.D30_REVENUE_POSITION_BASED, 0) AS D30_REVENUE_POSITION_BASED
         , COALESCE(a.D30_REVENUE_RECOMMENDED, 0) AS D30_REVENUE_RECOMMENDED

         -- D180 Revenue by model
         , COALESCE(a.D180_REVENUE_LAST_TOUCH, 0) AS D180_REVENUE_LAST_TOUCH
         , COALESCE(a.D180_REVENUE_FIRST_TOUCH, 0) AS D180_REVENUE_FIRST_TOUCH
         , COALESCE(a.D180_REVENUE_LINEAR, 0) AS D180_REVENUE_LINEAR
         , COALESCE(a.D180_REVENUE_TIME_DECAY, 0) AS D180_REVENUE_TIME_DECAY
         , COALESCE(a.D180_REVENUE_POSITION_BASED, 0) AS D180_REVENUE_POSITION_BASED
         , COALESCE(a.D180_REVENUE_RECOMMENDED, 0) AS D180_REVENUE_RECOMMENDED

         -- D365 Revenue by model
         , COALESCE(a.D365_REVENUE_LAST_TOUCH, 0) AS D365_REVENUE_LAST_TOUCH
         , COALESCE(a.D365_REVENUE_FIRST_TOUCH, 0) AS D365_REVENUE_FIRST_TOUCH
         , COALESCE(a.D365_REVENUE_LINEAR, 0) AS D365_REVENUE_LINEAR
         , COALESCE(a.D365_REVENUE_TIME_DECAY, 0) AS D365_REVENUE_TIME_DECAY
         , COALESCE(a.D365_REVENUE_POSITION_BASED, 0) AS D365_REVENUE_POSITION_BASED
         , COALESCE(a.D365_REVENUE_RECOMMENDED, 0) AS D365_REVENUE_RECOMMENDED

         -- Total Revenue by model
         , COALESCE(a.TOTAL_REVENUE_LAST_TOUCH, 0) AS TOTAL_REVENUE_LAST_TOUCH
         , COALESCE(a.TOTAL_REVENUE_FIRST_TOUCH, 0) AS TOTAL_REVENUE_FIRST_TOUCH
         , COALESCE(a.TOTAL_REVENUE_LINEAR, 0) AS TOTAL_REVENUE_LINEAR
         , COALESCE(a.TOTAL_REVENUE_TIME_DECAY, 0) AS TOTAL_REVENUE_TIME_DECAY
         , COALESCE(a.TOTAL_REVENUE_POSITION_BASED, 0) AS TOTAL_REVENUE_POSITION_BASED
         , COALESCE(a.TOTAL_REVENUE_RECOMMENDED, 0) AS TOTAL_REVENUE_RECOMMENDED

         -- Coverage
         , COALESCE(a.UNIQUE_DEVICES, 0) AS UNIQUE_DEVICES
         , COALESCE(a.DEVICES_WITH_USER_MAPPING, 0) AS DEVICES_WITH_USER_MAPPING

         -- Matured device counts
         , COALESCE(a.D1_MATURED_DEVICES, 0) AS D1_MATURED_DEVICES
         , COALESCE(a.D7_MATURED_DEVICES, 0) AS D7_MATURED_DEVICES
         , COALESCE(a.D30_MATURED_DEVICES, 0) AS D30_MATURED_DEVICES
         , COALESCE(a.D180_MATURED_DEVICES, 0) AS D180_MATURED_DEVICES
         , COALESCE(a.D365_MATURED_DEVICES, 0) AS D365_MATURED_DEVICES

         , COALESCE(s.COST, 0) > 0 AND COALESCE(a.UNIQUE_DEVICES, 0) = 0 AS HAS_SPEND_NO_MTA

    FROM campaign_aggregated a
    FULL OUTER JOIN spend s
        ON a.CAMPAIGN_ID = s.CAMPAIGN_ID
        AND a.PLATFORM = s.PLATFORM
        AND a.DATE = s.DATE
        AND a.AD_PARTNER = s.AD_PARTNER
)

SELECT *
     -- =============================================
     -- CPI BY MODEL (Cost Per Install)
     -- =============================================
     , IFF(INSTALLS_LAST_TOUCH > 0, COST / INSTALLS_LAST_TOUCH, NULL) AS CPI_LAST_TOUCH
     , IFF(INSTALLS_FIRST_TOUCH > 0, COST / INSTALLS_FIRST_TOUCH, NULL) AS CPI_FIRST_TOUCH
     , IFF(INSTALLS_LINEAR > 0, COST / INSTALLS_LINEAR, NULL) AS CPI_LINEAR
     , IFF(INSTALLS_TIME_DECAY > 0, COST / INSTALLS_TIME_DECAY, NULL) AS CPI_TIME_DECAY
     , IFF(INSTALLS_POSITION_BASED > 0, COST / INSTALLS_POSITION_BASED, NULL) AS CPI_POSITION_BASED
     , IFF(INSTALLS_RECOMMENDED > 0, COST / INSTALLS_RECOMMENDED, NULL) AS CPI_RECOMMENDED

     -- =============================================
     -- D1 ROAS BY MODEL
     -- =============================================
     , IFF(COST > 0, D1_REVENUE_LAST_TOUCH / COST, NULL) AS D1_ROAS_LAST_TOUCH
     , IFF(COST > 0, D1_REVENUE_FIRST_TOUCH / COST, NULL) AS D1_ROAS_FIRST_TOUCH
     , IFF(COST > 0, D1_REVENUE_LINEAR / COST, NULL) AS D1_ROAS_LINEAR
     , IFF(COST > 0, D1_REVENUE_TIME_DECAY / COST, NULL) AS D1_ROAS_TIME_DECAY
     , IFF(COST > 0, D1_REVENUE_POSITION_BASED / COST, NULL) AS D1_ROAS_POSITION_BASED
     , IFF(COST > 0, D1_REVENUE_RECOMMENDED / COST, NULL) AS D1_ROAS_RECOMMENDED

     -- =============================================
     -- D7 ROAS BY MODEL
     -- =============================================
     , IFF(COST > 0, D7_REVENUE_LAST_TOUCH / COST, NULL) AS D7_ROAS_LAST_TOUCH
     , IFF(COST > 0, D7_REVENUE_FIRST_TOUCH / COST, NULL) AS D7_ROAS_FIRST_TOUCH
     , IFF(COST > 0, D7_REVENUE_LINEAR / COST, NULL) AS D7_ROAS_LINEAR
     , IFF(COST > 0, D7_REVENUE_TIME_DECAY / COST, NULL) AS D7_ROAS_TIME_DECAY
     , IFF(COST > 0, D7_REVENUE_POSITION_BASED / COST, NULL) AS D7_ROAS_POSITION_BASED
     , IFF(COST > 0, D7_REVENUE_RECOMMENDED / COST, NULL) AS D7_ROAS_RECOMMENDED

     -- =============================================
     -- D30 ROAS BY MODEL
     -- =============================================
     , IFF(COST > 0, D30_REVENUE_LAST_TOUCH / COST, NULL) AS D30_ROAS_LAST_TOUCH
     , IFF(COST > 0, D30_REVENUE_FIRST_TOUCH / COST, NULL) AS D30_ROAS_FIRST_TOUCH
     , IFF(COST > 0, D30_REVENUE_LINEAR / COST, NULL) AS D30_ROAS_LINEAR
     , IFF(COST > 0, D30_REVENUE_TIME_DECAY / COST, NULL) AS D30_ROAS_TIME_DECAY
     , IFF(COST > 0, D30_REVENUE_POSITION_BASED / COST, NULL) AS D30_ROAS_POSITION_BASED
     , IFF(COST > 0, D30_REVENUE_RECOMMENDED / COST, NULL) AS D30_ROAS_RECOMMENDED

     -- =============================================
     -- D180 ROAS BY MODEL
     -- =============================================
     , IFF(COST > 0, D180_REVENUE_LAST_TOUCH / COST, NULL) AS D180_ROAS_LAST_TOUCH
     , IFF(COST > 0, D180_REVENUE_FIRST_TOUCH / COST, NULL) AS D180_ROAS_FIRST_TOUCH
     , IFF(COST > 0, D180_REVENUE_LINEAR / COST, NULL) AS D180_ROAS_LINEAR
     , IFF(COST > 0, D180_REVENUE_TIME_DECAY / COST, NULL) AS D180_ROAS_TIME_DECAY
     , IFF(COST > 0, D180_REVENUE_POSITION_BASED / COST, NULL) AS D180_ROAS_POSITION_BASED
     , IFF(COST > 0, D180_REVENUE_RECOMMENDED / COST, NULL) AS D180_ROAS_RECOMMENDED

     -- =============================================
     -- D365 ROAS BY MODEL
     -- =============================================
     , IFF(COST > 0, D365_REVENUE_LAST_TOUCH / COST, NULL) AS D365_ROAS_LAST_TOUCH
     , IFF(COST > 0, D365_REVENUE_FIRST_TOUCH / COST, NULL) AS D365_ROAS_FIRST_TOUCH
     , IFF(COST > 0, D365_REVENUE_LINEAR / COST, NULL) AS D365_ROAS_LINEAR
     , IFF(COST > 0, D365_REVENUE_TIME_DECAY / COST, NULL) AS D365_ROAS_TIME_DECAY
     , IFF(COST > 0, D365_REVENUE_POSITION_BASED / COST, NULL) AS D365_ROAS_POSITION_BASED
     , IFF(COST > 0, D365_REVENUE_RECOMMENDED / COST, NULL) AS D365_ROAS_RECOMMENDED

     -- =============================================
     -- LTV PER INSTALL BY MODEL (using recommended/time-decay)
     -- =============================================
     , IFF(INSTALLS_RECOMMENDED > 0, D1_REVENUE_RECOMMENDED / INSTALLS_RECOMMENDED, NULL) AS D1_LTV_PER_INSTALL
     , IFF(INSTALLS_RECOMMENDED > 0, D7_REVENUE_RECOMMENDED / INSTALLS_RECOMMENDED, NULL) AS D7_LTV_PER_INSTALL
     , IFF(INSTALLS_RECOMMENDED > 0, D30_REVENUE_RECOMMENDED / INSTALLS_RECOMMENDED, NULL) AS D30_LTV_PER_INSTALL
     , IFF(INSTALLS_RECOMMENDED > 0, D180_REVENUE_RECOMMENDED / INSTALLS_RECOMMENDED, NULL) AS D180_LTV_PER_INSTALL
     , IFF(INSTALLS_RECOMMENDED > 0, D365_REVENUE_RECOMMENDED / INSTALLS_RECOMMENDED, NULL) AS D365_LTV_PER_INSTALL
     , IFF(INSTALLS_RECOMMENDED > 0, TOTAL_REVENUE_RECOMMENDED / INSTALLS_RECOMMENDED, NULL) AS TOTAL_LTV_PER_INSTALL

FROM final
WHERE DATE IS NOT NULL
ORDER BY DATE DESC, COST DESC
