SELECT DATE
     , PARTNER_NAME
     , CAMPAIGN_ID_NETWORK
     , CAMPAIGN_NETWORK
     , ADGROUP_ID_NETWORK
     , ADGROUP_NETWORK
     , AD_ID
     , AD_NAME
     , COUNTRY
     , OS_NAME
     , APP
     , REGION
     , SUM(NETWORK_COST) AS SPEND
     , SUM(CLICKS) AS CLICKS
     , SUM(IMPRESSIONS) AS IMPRESSIONS
     , SUM(INSTALLS) AS INSTALLS
     , SUM(SESSIONS) AS SESSIONS
     , SUM(BASE_SESSIONS) AS BASE_SESSIONS
     , SUM(EVENTS) AS EVENTS
     , SUM(REATTRIBUTIONS) AS REATTRIBUTIONS
     , SUM(REATTRIBUTION_REINSTALLS) AS REATTRIBUTION_REINSTALLS
     , SUM(DEATTRIBUTIONS) AS DEATTRIBUTIONS
     , SUM(REINSTALLS) AS REINSTALLS
     , SUM(UNINSTALLS) AS UNINSTALLS
     , SUM(C_DATASCAPE_BUNDLE_PURCHASE_EVENTS) AS BUNDLE_PURCHASE_EVENTS
     , SUM(C_DATASCAPE_BUNDLE_PURCHASE_REVENUE) AS BUNDLE_PURCHASE_REVENUE
     , SUM(C_DATASCAPE_COIN_PURCHASE_EVENTS) AS COIN_PURCHASE_EVENTS
     , SUM(C_DATASCAPE_COIN_PURCHASE_REVENUE) AS COIN_PURCHASE_REVENUE
     , SUM(C_DATASCAPE_CREDIT_PURCHASE_EVENTS) AS CREDIT_PURCHASE_EVENTS
     , SUM(C_DATASCAPE_CREDIT_PURCHASE_REVENUE) AS CREDIT_PURCHASE_REVENUE
     , SUM(C_DATASCAPE_PLAYFORCASHCLICK_EVENTS) AS PLAYFORCASHCLICK_EVENTS
     , SUM(C_DATASCAPE_PLAYFORCASHCLICK_REVENUE) AS PLAYFORCASHCLICK_REVENUE
     , SUM(C_DATASCAPE_REGISTRATION_EVENTS) AS REGISTRATION_EVENTS
     , SUM(C_DATASCAPE_TUTORIAL_COMPLETED_EVENTS) AS TUTORIAL_COMPLETED_EVENTS
     , SUM(C_DATASCAPE_TUTORIAL_COMPLETED_REVENUE) AS TUTORIAL_COMPLETED_REVENUE
     , SUM(C_DATASCAPE_REACHLEVEL_5_EVENTS) AS REACHLEVEL_5_EVENTS
     , SUM(C_DATASCAPE_REACHLEVEL_5_REVENUE) AS REACHLEVEL_5_REVENUE
     , SUM(C_DATASCAPE_REACHLEVEL_10_EVENTS) AS REACHLEVEL_10_EVENTS
     , SUM(C_DATASCAPE_REACHLEVEL_10_REVENUE) AS REACHLEVEL_10_REVENUE
     , SUM(C_DATASCAPE_REACHLEVEL_20_EVENTS) AS REACHLEVEL_20_EVENTS
     , SUM(C_DATASCAPE_REACHLEVEL_20_REVENUE) AS REACHLEVEL_20_REVENUE
     , SUM(C_DATASCAPE_REACHLEVEL_30_EVENTS) AS REACHLEVEL_30_EVENTS
     , SUM(C_DATASCAPE_REACHLEVEL_30_REVENUE) AS REACHLEVEL_30_REVENUE
     , SUM(C_DATASCAPE_REACHLEVEL_40_EVENTS) AS REACHLEVEL_40_EVENTS
     , SUM(C_DATASCAPE_REACHLEVEL_40_REVENUE) AS REACHLEVEL_40_REVENUE
     , SUM(C_DATASCAPE_REACHLEVEL_50_EVENTS) AS REACHLEVEL_50_EVENTS
     , SUM(C_DATASCAPE_REACHLEVEL_50_REVENUE) AS REACHLEVEL_50_REVENUE
     , SUM(C_DATASCAPE_REACHLEVEL_60_EVENTS) AS REACHLEVEL_60_EVENTS
     , SUM(C_DATASCAPE_REACHLEVEL_60_REVENUE) AS REACHLEVEL_60_REVENUE
     , SUM(C_DATASCAPE_REACHLEVEL_70_EVENTS) AS REACHLEVEL_70_EVENTS
     , SUM(C_DATASCAPE_REACHLEVEL_70_REVENUE) AS REACHLEVEL_70_REVENUE
     , SUM(C_DATASCAPE_REACHLEVEL_80_EVENTS) AS REACHLEVEL_80_EVENTS
     , SUM(C_DATASCAPE_REACHLEVEL_80_REVENUE) AS REACHLEVEL_80_REVENUE
     , SUM(C_DATASCAPE_REACHLEVEL_90_EVENTS) AS REACHLEVEL_90_EVENTS
     , SUM(C_DATASCAPE_REACHLEVEL_90_REVENUE) AS REACHLEVEL_90_REVENUE
     , SUM(C_DATASCAPE_REACHLEVEL_100_EVENTS) AS REACHLEVEL_100_EVENTS
     , SUM(C_DATASCAPE_REACHLEVEL_100_REVENUE) AS REACHLEVEL_100_REVENUE
     , SUM(C_DATASCAPE_REACHLEVEL_110_EVENTS) AS REACHLEVEL_110_EVENTS
     , SUM(C_DATASCAPE_REACHLEVEL_110_REVENUE) AS REACHLEVEL_110_REVENUE
FROM SUPERMETRICS.DATA_TRANSFERS.ADJ_CAMPAIGN
WHERE DATE >= '01/01/2025'
GROUP BY DATE
     , PARTNER_NAME
     , CAMPAIGN_ID_NETWORK
     , CAMPAIGN_NETWORK
     , ADGROUP_ID_NETWORK
     , ADGROUP_NETWORK
     , AD_ID
     , AD_NAME
     , COUNTRY_CODE
     , COUNTRY
     , CURRENCY_CODE
     , DEVICE_TYPE
     , OS_NAME
     , APP
     , STORE_ID
     , STORE_TYPE
     , REGION
 ORDER BY DATE DESC