/*
 * Amplitude EVENTS_726530 Full Column List
 *
 * PURPOSE: List all columns to identify any device-related fields we might have missed.
 * SERIES: amplitude_04 of 08
 */

SELECT
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    ORDINAL_POSITION
FROM AMPLITUDEANALYTICS_AMPLITUDE_DB_364926_SHARE.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SCHEMA_726530'
  AND TABLE_NAME = 'EVENTS_726530'
ORDER BY ORDINAL_POSITION
