/*
 * MERGE_IDS Table Structure Investigation
 *
 * PURPOSE: Check what columns exist in the MERGE_IDS table.
 * SERIES: amplitude_05 of 08
 */

SELECT
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    ORDINAL_POSITION
FROM AMPLITUDEANALYTICS_AMPLITUDE_DB_364926_SHARE.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SCHEMA_726530'
  AND TABLE_NAME = 'MERGE_IDS_726530'
ORDER BY ORDINAL_POSITION
