/*
 * Amplitude ADID Field Investigation
 *
 * PURPOSE: Check if EVENTS table has any columns containing 'ADID', 'ADVERTISING', or related terms.
 * SERIES: amplitude_03 of 08
 */

SELECT
    TABLE_CATALOG,
    TABLE_SCHEMA,
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    ORDINAL_POSITION
FROM AMPLITUDEANALYTICS_AMPLITUDE_DB_364926_SHARE.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'SCHEMA_726530'
  AND TABLE_NAME = 'EVENTS_726530'
  AND (
      UPPER(COLUMN_NAME) LIKE '%ADID%'
      OR UPPER(COLUMN_NAME) LIKE '%ADVERTISING%'
      OR UPPER(COLUMN_NAME) LIKE '%DEVICE_ID%'
      OR UPPER(COLUMN_NAME) LIKE '%GPS%'
      OR UPPER(COLUMN_NAME) LIKE '%GAID%'
      OR UPPER(COLUMN_NAME) LIKE '%IDFA%'
      OR UPPER(COLUMN_NAME) LIKE '%IDFV%'
  )
ORDER BY ORDINAL_POSITION
