{{
    config(
        materialized='view',
        schema='staging'
    )
}}

/*
    Staging model for Adjust API daily report data
    Source: ADJUST.API_DATA.REPORT_DAILY_RAW

    This replaces Supermetrics as the spend data source starting 2021-04-07
*/

SELECT DAY AS DATE
     , APP
     , REGION
     , COUNTRY
     , COUNTRY_CODE
     , DEVICE_TYPE
     , OS_NAME
     , CASE
         WHEN UPPER(OS_NAME) = 'IOS' THEN 'iOS'
         WHEN UPPER(OS_NAME) = 'ANDROID' THEN 'Android'
         ELSE OS_NAME
       END AS PLATFORM
     , CHANNEL
     , NETWORK AS PARTNER_NAME
     , STORE_TYPE
     , STORE_ID
     , CAMPAIGN
     , TRIM(REGEXP_REPLACE(CAMPAIGN_NETWORK, '\\s*\\([a-zA-Z0-9_-]+\\)\\s*$', '')) AS CAMPAIGN_NETWORK
     , CAMPAIGN_ID_NETWORK
     , ADGROUP
     , TRIM(REGEXP_REPLACE(ADGROUP_NETWORK, '\\s*\\([a-zA-Z0-9_-]+\\)\\s*$', '')) AS ADGROUP_NETWORK
     , ADGROUP_ID_NETWORK
     , CREATIVE
     , CREATIVE_NETWORK
     , CREATIVE_ID_NETWORK
     , SOURCE_NETWORK
     , SOURCE_ID_NETWORK
     , COALESCE(IMPRESSIONS, 0) AS IMPRESSIONS
     , COALESCE(CLICKS, 0) AS CLICKS
     , COALESCE(INSTALLS, 0) AS INSTALLS
     , COALESCE(NETWORK_COST, 0) AS NETWORK_COST
     , COALESCE(COST, 0) AS COST
     , COALESCE(ADJUST_COST, 0) AS ADJUST_COST
     , COALESCE(REVENUE, 0) AS REVENUE
     , COALESCE(ALL_REVENUE, 0) AS ALL_REVENUE
     , COALESCE(PAID_CLICKS, 0) AS PAID_CLICKS
     , COALESCE(PAID_IMPRESSIONS, 0) AS PAID_IMPRESSIONS
     , COALESCE(PAID_INSTALLS, 0) AS PAID_INSTALLS
     , COALESCE(EVENTS, 0) AS EVENTS
     , COALESCE(SESSIONS, 0) AS SESSIONS
     , COALESCE(BASE_SESSIONS, 0) AS BASE_SESSIONS
     , COALESCE(UNINSTALLS, 0) AS UNINSTALLS
     , COALESCE(REATTRIBUTIONS, 0) AS REATTRIBUTIONS
     , COALESCE(REATTRIBUTION_REINSTALLS, 0) AS REATTRIBUTION_REINSTALLS
     , COALESCE(DEATTRIBUTIONS, 0) AS DEATTRIBUTIONS
     , COALESCE(REINSTALLS, 0) AS REINSTALLS
     , COALESCE(AD_REVENUE, 0) AS AD_REVENUE
FROM {{ source('adjust_api_data', 'REPORT_DAILY_RAW') }}
WHERE DAY IS NOT NULL
