WITH IOS_INSTALLS AS (
    SELECT IDFV AS DEVICE_ID
         , 'iOS' AS PLATFORM
         , NETWORK_NAME
         , CAMPAIGN_NAME
         , REGEXP_SUBSTR(CAMPAIGN_NAME, '\\(([0-9]+)\\)$', 1, 1, 'e') AS CAMPAIGN_ID
         , ADGROUP_NAME
         , REGEXP_SUBSTR(ADGROUP_NAME, '\\(([0-9]+)\\)$', 1, 1, 'e') AS ADGROUP_ID
         , CREATIVE_NAME
         , TRACKER_NAME
         , COUNTRY
         , TO_TIMESTAMP(INSTALLED_AT) AS INSTALL_TIMESTAMP
         , TO_TIMESTAMP(CREATED_AT) AS CREATED_TIMESTAMP
    FROM ADJUST_S3.DATA.IOS_ACTIVITY_INSTALL
    WHERE IDFV IS NOT NULL
      AND INSTALLED_AT IS NOT NULL
)

, ANDROID_INSTALLS AS (
    SELECT GPS_ADID AS DEVICE_ID
         , 'Android' AS PLATFORM
         , NETWORK_NAME
         , CAMPAIGN_NAME
         , REGEXP_SUBSTR(CAMPAIGN_NAME, '\\(([0-9]+)\\)$', 1, 1, 'e') AS CAMPAIGN_ID
         , ADGROUP_NAME
         , REGEXP_SUBSTR(ADGROUP_NAME, '\\(([0-9]+)\\)$', 1, 1, 'e') AS ADGROUP_ID
         , CREATIVE_NAME
         , NULL AS TRACKER_NAME
         , NULL AS COUNTRY
         , TO_TIMESTAMP(INSTALLED_AT) AS INSTALL_TIMESTAMP
         , TO_TIMESTAMP(CREATED_AT) AS CREATED_TIMESTAMP
    FROM ADJUST_S3.DATA.ANDROID_ACTIVITY_INSTALL
    WHERE GPS_ADID IS NOT NULL
      AND INSTALLED_AT IS NOT NULL
)

, COMBINED AS (
    SELECT * FROM IOS_INSTALLS
    UNION ALL
    SELECT * FROM ANDROID_INSTALLS
)

, DEDUPED AS (
    SELECT *
    FROM COMBINED
    QUALIFY ROW_NUMBER() OVER (PARTITION BY DEVICE_ID, PLATFORM ORDER BY INSTALL_TIMESTAMP ASC) = 1
)

SELECT *
FROM DEDUPED
