{{ config(
    materialized='table',
    tags=['mmm', 'mart', 'summary', 'weekly']
) }}

-- mmm__weekly_channel_summary.sql
-- Weekly rollup of daily channel summary for MMM tools preferring weekly data
-- Some MMM implementations (especially with limited history) work better at weekly grain
-- Grain: one row per WEEK_START_DATE + PLATFORM + CHANNEL

SELECT
    DATE_TRUNC('week', DATE) AS WEEK_START_DATE,
    PLATFORM,
    CHANNEL,

    -- Spend metrics (sum over week)
    SUM(SPEND) AS SPEND,
    SUM(IMPRESSIONS) AS IMPRESSIONS,
    SUM(CLICKS) AS CLICKS,
    SUM(PAID_INSTALLS) AS PAID_INSTALLS,
    SUM(PAID_CLICKS) AS PAID_CLICKS,
    SUM(PAID_IMPRESSIONS) AS PAID_IMPRESSIONS,
    SUM(SESSIONS) AS SESSIONS,
    SUM(REATTRIBUTIONS) AS REATTRIBUTIONS,

    -- Install metrics (sum over week)
    SUM(INSTALLS) AS INSTALLS,

    -- Revenue metrics (sum over week)
    SUM(REVENUE) AS REVENUE,
    SUM(ALL_REVENUE) AS ALL_REVENUE,
    SUM(AD_REVENUE) AS AD_REVENUE,
    SUM(INSTALLS_API) AS INSTALLS_API,

    -- SKAN metrics (sum over week, iOS only)
    SUM(SKAN_INSTALLS) AS SKAN_INSTALLS,
    SUM(SKAN_NEW_INSTALLS) AS SKAN_NEW_INSTALLS,
    SUM(SKAN_REDOWNLOADS) AS SKAN_REDOWNLOADS,
    AVG(NULLIF(SKAN_AVG_CV, 0)) AS SKAN_AVG_CV,
    SUM(SKAN_INSTALLS_WITH_CV) AS SKAN_INSTALLS_WITH_CV,
    SUM(SKAN_CV_BUCKET_0) AS SKAN_CV_BUCKET_0,
    SUM(SKAN_CV_BUCKET_1_10) AS SKAN_CV_BUCKET_1_10,
    SUM(SKAN_CV_BUCKET_11_20) AS SKAN_CV_BUCKET_11_20,
    SUM(SKAN_CV_BUCKET_21_40) AS SKAN_CV_BUCKET_21_40,
    SUM(SKAN_CV_BUCKET_41_63) AS SKAN_CV_BUCKET_41_63,
    SUM(SKAN_STOREKIT_RENDERED) AS SKAN_STOREKIT_RENDERED,
    SUM(SKAN_VIEW_THROUGH) AS SKAN_VIEW_THROUGH,
    SUM(SKAN_WINNING_POSTBACKS) AS SKAN_WINNING_POSTBACKS,
    SUM(SKAN_V3_COUNT) AS SKAN_V3_COUNT,
    SUM(SKAN_V4_COUNT) AS SKAN_V4_COUNT,

    -- Weekly KPIs (recomputed, not averaged)
    CASE WHEN SUM(INSTALLS) > 0
         THEN SUM(SPEND) / SUM(INSTALLS)
         ELSE NULL
    END AS CPI,

    CASE WHEN SUM(SPEND) > 0
         THEN SUM(REVENUE) / SUM(SPEND)
         ELSE NULL
    END AS ROAS,

    CASE WHEN SUM(SPEND) > 0
         THEN SUM(ALL_REVENUE) / SUM(SPEND)
         ELSE NULL
    END AS ALL_ROAS,

    -- Data coverage for the week
    SUM(HAS_SPEND_DATA) AS DAYS_WITH_SPEND,
    SUM(HAS_INSTALL_DATA) AS DAYS_WITH_INSTALLS,
    SUM(HAS_REVENUE_DATA) AS DAYS_WITH_REVENUE,
    SUM(HAS_SKAN_DATA) AS DAYS_WITH_SKAN,
    COUNT(*) AS DAYS_IN_WEEK

FROM {{ ref('mmm__daily_channel_summary') }}
GROUP BY 1, 2, 3
ORDER BY 1 DESC, 2, 3
