{{ config(
    materialized='incremental',
    unique_key=['DATE', 'PARTNER_ID', 'PLATFORM', 'CAMPAIGN_ID_NETWORK', 'ADGROUP_ID_NETWORK', 'AD_ID'],
    incremental_strategy='merge'
) }}

WITH SOURCE AS (

    SELECT *
    FROM {{ source('supermetrics', 'adj_campaign') }}
    {% if is_incremental() %}
    WHERE DATE >= (SELECT MAX(DATE) - INTERVAL '3 DAYS' FROM {{ this }})
    {% endif %}

)

, AGGREGATED AS (

    SELECT DATE
         , PARTNER_ID
         , PARTNER_NAME
         , PLATFORM
         , CAMPAIGN_ID_NETWORK
         , CAMPAIGN_NETWORK
         , ADGROUP_ID_NETWORK
         , ADGROUP_NETWORK
         , AD_ID
         , AD_NAME
         , COUNTRY_CODE
         , COUNTRY
         , CURRENCY_CODE
         , DEVICE_TYPE
         , OS_NAME
         , APP
         , STORE_ID
         , STORE_TYPE
         , REGION
         , SUM(COST) AS COST
         , SUM(CLICKS) AS CLICKS
         , SUM(PAID_CLICKS) AS PAID_CLICKS
         , SUM(IMPRESSIONS) AS IMPRESSIONS
         , SUM(PAID_IMPRESSIONS) AS PAID_IMPRESSIONS
         , SUM(INSTALLS) AS INSTALLS
         , SUM(PAID_INSTALLS) AS PAID_INSTALLS
         , SUM(SESSIONS) AS SESSIONS
         , SUM(BASE_SESSIONS) AS BASE_SESSIONS
         , SUM(EVENTS) AS EVENTS
         , SUM(REATTRIBUTIONS) AS REATTRIBUTIONS
         , SUM(REATTRIBUTION_REINSTALLS) AS REATTRIBUTION_REINSTALLS
         , SUM(DEATTRIBUTIONS) AS DEATTRIBUTIONS
         , SUM(REINSTALLS) AS REINSTALLS
         , SUM(UNINSTALLS) AS UNINSTALLS
         , SUM(BUNDLE_PURCHASE_EVENTS) AS BUNDLE_PURCHASE_EVENTS
         , SUM(BUNDLE_PURCHASE_REVENUE) AS BUNDLE_PURCHASE_REVENUE
         , SUM(COIN_PURCHASE_EVENTS) AS COIN_PURCHASE_EVENTS
         , SUM(COIN_PURCHASE_REVENUE) AS COIN_PURCHASE_REVENUE
         , SUM(CREDIT_PURCHASE_EVENTS) AS CREDIT_PURCHASE_EVENTS
         , SUM(CREDIT_PURCHASE_REVENUE) AS CREDIT_PURCHASE_REVENUE
         , SUM(PLAYFORCASHCLICK_EVENTS) AS PLAYFORCASHCLICK_EVENTS
         , SUM(PLAYFORCASHCLICK_REVENUE) AS PLAYFORCASHCLICK_REVENUE
         , SUM(REGISTRATION_EVENTS) AS REGISTRATION_EVENTS
         , SUM(REGISTRATION_REVENUE) AS REGISTRATION_REVENUE
         , SUM(TUTORIAL_COMPLETED_EVENTS) AS TUTORIAL_COMPLETED_EVENTS
         , SUM(TUTORIAL_COMPLETED_REVENUE) AS TUTORIAL_COMPLETED_REVENUE
         , SUM(REACHLEVEL_5_EVENTS) AS REACHLEVEL_5_EVENTS
         , SUM(REACHLEVEL_5_REVENUE) AS REACHLEVEL_5_REVENUE
         , SUM(REACHLEVEL_10_EVENTS) AS REACHLEVEL_10_EVENTS
         , SUM(REACHLEVEL_10_REVENUE) AS REACHLEVEL_10_REVENUE
         , SUM(REACHLEVEL_20_EVENTS) AS REACHLEVEL_20_EVENTS
         , SUM(REACHLEVEL_20_REVENUE) AS REACHLEVEL_20_REVENUE
         , SUM(REACHLEVEL_30_EVENTS) AS REACHLEVEL_30_EVENTS
         , SUM(REACHLEVEL_30_REVENUE) AS REACHLEVEL_30_REVENUE
         , SUM(REACHLEVEL_40_EVENTS) AS REACHLEVEL_40_EVENTS
         , SUM(REACHLEVEL_40_REVENUE) AS REACHLEVEL_40_REVENUE
         , SUM(REACHLEVEL_50_EVENTS) AS REACHLEVEL_50_EVENTS
         , SUM(REACHLEVEL_50_REVENUE) AS REACHLEVEL_50_REVENUE
         , SUM(REACHLEVEL_60_EVENTS) AS REACHLEVEL_60_EVENTS
         , SUM(REACHLEVEL_60_REVENUE) AS REACHLEVEL_60_REVENUE
         , SUM(REACHLEVEL_70_EVENTS) AS REACHLEVEL_70_EVENTS
         , SUM(REACHLEVEL_70_REVENUE) AS REACHLEVEL_70_REVENUE
         , SUM(REACHLEVEL_80_EVENTS) AS REACHLEVEL_80_EVENTS
         , SUM(REACHLEVEL_80_REVENUE) AS REACHLEVEL_80_REVENUE
         , SUM(REACHLEVEL_90_EVENTS) AS REACHLEVEL_90_EVENTS
         , SUM(REACHLEVEL_90_REVENUE) AS REACHLEVEL_90_REVENUE
         , SUM(REACHLEVEL_100_EVENTS) AS REACHLEVEL_100_EVENTS
         , SUM(REACHLEVEL_100_REVENUE) AS REACHLEVEL_100_REVENUE
         , SUM(REACHLEVEL_110_EVENTS) AS REACHLEVEL_110_EVENTS
         , SUM(REACHLEVEL_110_REVENUE) AS REACHLEVEL_110_REVENUE
    FROM SOURCE
    GROUP BY DATE
         , PARTNER_ID
         , PARTNER_NAME
         , PLATFORM
         , CAMPAIGN_ID_NETWORK
         , CAMPAIGN_NETWORK
         , ADGROUP_ID_NETWORK
         , ADGROUP_NETWORK
         , AD_ID
         , AD_NAME
         , COUNTRY_CODE
         , COUNTRY
         , CURRENCY_CODE
         , DEVICE_TYPE
         , OS_NAME
         , APP
         , STORE_ID
         , STORE_TYPE
         , REGION

)

SELECT *
FROM AGGREGATED
