-- Adjust API Integration - Table Setup
-- Creates the schema and tables we need to store data from the Adjust API
-- This mirrors the structure we had in Supermetrics

USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE WGT;

CREATE SCHEMA IF NOT EXISTS ADJUST_API;
USE SCHEMA ADJUST_API;

-- Main table for campaign data (same structure as SUPERMETRICS.DATA_TRANSFERS.ADJ_CAMPAIGN)
CREATE TABLE IF NOT EXISTS ADJ_CAMPAIGN_API (
    -- Dimensions
    AD_ID                   VARCHAR(256),
    AD_NAME                 VARCHAR(1024),
    ADGROUP_ID_NETWORK      VARCHAR(256),
    ADGROUP_NETWORK         VARCHAR(1024),
    APP                     VARCHAR(256),
    CAMPAIGN_ID_NETWORK     VARCHAR(256),
    CAMPAIGN_NETWORK        VARCHAR(1024),
    COUNTRY                 VARCHAR(256),
    COUNTRY_CODE            VARCHAR(2),
    CURRENCY_CODE           VARCHAR(3),
    DATE                    DATE,
    DEVICE_TYPE             VARCHAR(64),
    OS_NAME                 VARCHAR(64),
    PARTNER_ID              VARCHAR(256),
    PARTNER_NAME            VARCHAR(256),
    PLATFORM                VARCHAR(64),
    REGION                  VARCHAR(256),
    STORE_ID                VARCHAR(256),
    STORE_TYPE              VARCHAR(64),
    DATA_SOURCE_NAME        VARCHAR(64) DEFAULT 'Adjust API',

    -- WGT custom events
    C_DATASCAPE_BUNDLE_PURCHASE_EVENTS          NUMBER(38,0),
    C_DATASCAPE_BUNDLE_PURCHASE_REVENUE         FLOAT,
    C_DATASCAPE_COIN_PURCHASE_EVENTS            NUMBER(38,0),
    C_DATASCAPE_COIN_PURCHASE_REVENUE           FLOAT,
    C_DATASCAPE_CREDIT_PURCHASE_EVENTS          NUMBER(38,0),
    C_DATASCAPE_CREDIT_PURCHASE_REVENUE         FLOAT,
    C_DATASCAPE_PLAYFORCASHCLICK_EVENTS         NUMBER(38,0),
    C_DATASCAPE_PLAYFORCASHCLICK_REVENUE        FLOAT,
    C_DATASCAPE_REACHLEVEL_5_EVENTS             NUMBER(38,0),
    C_DATASCAPE_REACHLEVEL_5_REVENUE            FLOAT,
    C_DATASCAPE_REACHLEVEL_10_EVENTS            NUMBER(38,0),
    C_DATASCAPE_REACHLEVEL_10_REVENUE           FLOAT,
    C_DATASCAPE_REACHLEVEL_20_EVENTS            NUMBER(38,0),
    C_DATASCAPE_REACHLEVEL_20_REVENUE           FLOAT,
    C_DATASCAPE_REACHLEVEL_30_EVENTS            NUMBER(38,0),
    C_DATASCAPE_REACHLEVEL_30_REVENUE           FLOAT,
    C_DATASCAPE_REACHLEVEL_40_EVENTS            NUMBER(38,0),
    C_DATASCAPE_REACHLEVEL_40_REVENUE           FLOAT,
    C_DATASCAPE_REACHLEVEL_50_EVENTS            NUMBER(38,0),
    C_DATASCAPE_REACHLEVEL_50_REVENUE           FLOAT,
    C_DATASCAPE_REACHLEVEL_60_EVENTS            NUMBER(38,0),
    C_DATASCAPE_REACHLEVEL_60_REVENUE           FLOAT,
    C_DATASCAPE_REACHLEVEL_70_EVENTS            NUMBER(38,0),
    C_DATASCAPE_REACHLEVEL_70_REVENUE           FLOAT,
    C_DATASCAPE_REACHLEVEL_80_EVENTS            NUMBER(38,0),
    C_DATASCAPE_REACHLEVEL_80_REVENUE           FLOAT,
    C_DATASCAPE_REACHLEVEL_90_EVENTS            NUMBER(38,0),
    C_DATASCAPE_REACHLEVEL_90_REVENUE           FLOAT,
    C_DATASCAPE_REACHLEVEL_100_EVENTS           NUMBER(38,0),
    C_DATASCAPE_REACHLEVEL_100_REVENUE          FLOAT,
    C_DATASCAPE_REACHLEVEL_110_EVENTS           NUMBER(38,0),
    C_DATASCAPE_REACHLEVEL_110_REVENUE          FLOAT,
    C_DATASCAPE_REGISTRATION_EVENTS             NUMBER(38,0),
    C_DATASCAPE_TUTORIAL_COMPLETED_EVENTS       NUMBER(38,0),
    C_DATASCAPE_TUTORIAL_COMPLETED_REVENUE      FLOAT,

    -- Standard metrics
    ADJUST_COST             FLOAT,
    BASE_SESSIONS           NUMBER(38,0),
    CLICKS                  NUMBER(38,0),
    COST                    FLOAT,
    DEATTRIBUTIONS          NUMBER(38,0),
    EVENTS                  NUMBER(38,0),
    IMPRESSIONS             NUMBER(38,0),
    INSTALLS                NUMBER(38,0),
    NETWORK_COST            FLOAT,
    PAID_CLICKS             NUMBER(38,0),
    PAID_IMPRESSIONS        NUMBER(38,0),
    PAID_INSTALLS           NUMBER(38,0),
    REATTRIBUTION_REINSTALLS NUMBER(38,0),
    REATTRIBUTIONS          NUMBER(38,0),
    REINSTALLS              NUMBER(38,0),
    SESSIONS                NUMBER(38,0),
    UNINSTALLS              NUMBER(38,0),

    LOADED_AT               TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT pk_adj_campaign_api PRIMARY KEY (DATE, APP, OS_NAME, COUNTRY_CODE, PARTNER_ID, CAMPAIGN_ID_NETWORK, ADGROUP_ID_NETWORK, AD_ID)
);

-- Staging table for raw API responses
CREATE TABLE IF NOT EXISTS ADJ_CAMPAIGN_API_STAGING (
    RAW_JSON        VARIANT,
    API_CALL_DATE   DATE,
    LOADED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Store API credentials here
CREATE TABLE IF NOT EXISTS API_CREDENTIALS (
    CREDENTIAL_NAME     VARCHAR(256) PRIMARY KEY,
    CREDENTIAL_VALUE    VARCHAR(4096),
    DESCRIPTION         VARCHAR(1024),
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Placeholder for token - update with real value
INSERT INTO API_CREDENTIALS (CREDENTIAL_NAME, CREDENTIAL_VALUE, DESCRIPTION)
SELECT 'ADJUST_API_TOKEN', 'YOUR_ADJUST_API_TOKEN_HERE', 'Adjust API bearer token'
WHERE NOT EXISTS (SELECT 1 FROM API_CREDENTIALS WHERE CREDENTIAL_NAME = 'ADJUST_API_TOKEN');

-- Map app names to Adjust app tokens
CREATE TABLE IF NOT EXISTS APP_TOKEN_MAPPING (
    APP_NAME            VARCHAR(256) PRIMARY KEY,
    APP_TOKEN           VARCHAR(64),
    STORE_ID            VARCHAR(256),
    OS_NAME             VARCHAR(64),
    IS_ACTIVE           BOOLEAN DEFAULT TRUE,
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Add your apps here
INSERT INTO APP_TOKEN_MAPPING (APP_NAME, APP_TOKEN, STORE_ID, OS_NAME)
SELECT '1 - iOS Golf Mobile', 'YOUR_IOS_APP_TOKEN', '672828590', 'ios'
WHERE NOT EXISTS (SELECT 1 FROM APP_TOKEN_MAPPING WHERE APP_NAME = '1 - iOS Golf Mobile');

INSERT INTO APP_TOKEN_MAPPING (APP_NAME, APP_TOKEN, STORE_ID, OS_NAME)
SELECT '2 - Googleplay Golf Mobile', 'YOUR_ANDROID_APP_TOKEN', 'YOUR_ANDROID_STORE_ID', 'android'
WHERE NOT EXISTS (SELECT 1 FROM APP_TOKEN_MAPPING WHERE APP_NAME = '2 - Googleplay Golf Mobile');

-- Track load history
CREATE TABLE IF NOT EXISTS API_LOAD_LOG (
    LOG_ID              NUMBER AUTOINCREMENT,
    LOAD_DATE           DATE,
    APP_NAME            VARCHAR(256),
    STATUS              VARCHAR(64),
    ROWS_LOADED         NUMBER,
    ERROR_MESSAGE       VARCHAR(4096),
    STARTED_AT          TIMESTAMP_NTZ,
    COMPLETED_AT        TIMESTAMP_NTZ,
    DURATION_SECONDS    NUMBER
);

-- Permissions for dbt
GRANT USAGE ON SCHEMA WGT.ADJUST_API TO ROLE DBT_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA WGT.ADJUST_API TO ROLE DBT_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA WGT.ADJUST_API TO ROLE DBT_ROLE;
