-- ============================================================================
-- ADJUST API TO SNOWFLAKE INTEGRATION
-- Part 4: Stored Procedures for Data Loading
-- ============================================================================
-- These procedures handle the data extraction, transformation, and loading
-- ============================================================================

USE ROLE SYSADMIN;
USE DATABASE WGT;
USE SCHEMA ADJUST_API;

-- ============================================================================
-- 1. PROCEDURE: Load Single Day of Data
-- ============================================================================

CREATE OR REPLACE PROCEDURE load_adjust_data_for_date(
    p_date DATE,
    p_app_token VARCHAR,
    p_app_name VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    v_api_token VARCHAR;
    v_start_time TIMESTAMP_NTZ;
    v_rows_loaded INTEGER DEFAULT 0;
    v_error_message VARCHAR;
BEGIN
    v_start_time := CURRENT_TIMESTAMP();

    -- Get API token
    SELECT CREDENTIAL_VALUE INTO v_api_token
    FROM WGT.ADJUST_API.API_CREDENTIALS
    WHERE CREDENTIAL_NAME = 'ADJUST_API_TOKEN';

    IF (v_api_token IS NULL OR v_api_token = 'YOUR_ADJUST_API_TOKEN_HERE') THEN
        RETURN 'ERROR: API token not configured. Update API_CREDENTIALS table.';
    END IF;

    -- Call the Snowpark function and insert into staging
    INSERT INTO WGT.ADJUST_API.ADJ_CAMPAIGN_API_STAGING (RAW_JSON, API_CALL_DATE)
    SELECT
        fetch_adjust_data_snowpark(
            :v_api_token,
            :p_app_token,
            TO_VARCHAR(:p_date, 'YYYY-MM-DD'),
            TO_VARCHAR(:p_date, 'YYYY-MM-DD')
        ),
        :p_date;

    -- Parse and load into final table
    MERGE INTO WGT.ADJUST_API.ADJ_CAMPAIGN_API AS target
    USING (
        SELECT
            TO_DATE(f.value:DATE::VARCHAR) AS DATE,
            COALESCE(f.value:APP::VARCHAR, :p_app_name) AS APP,
            f.value:OS_NAME::VARCHAR AS OS_NAME,
            f.value:DEVICE_TYPE::VARCHAR AS DEVICE_TYPE,
            f.value:COUNTRY::VARCHAR AS COUNTRY,
            f.value:COUNTRY_CODE::VARCHAR AS COUNTRY_CODE,
            f.value:REGION::VARCHAR AS REGION,
            f.value:PARTNER_ID::VARCHAR AS PARTNER_ID,
            f.value:PARTNER_NAME::VARCHAR AS PARTNER_NAME,
            COALESCE(f.value:CAMPAIGN_ID_NETWORK::VARCHAR, 'unknown') AS CAMPAIGN_ID_NETWORK,
            COALESCE(f.value:CAMPAIGN_NETWORK::VARCHAR, 'unknown') AS CAMPAIGN_NETWORK,
            COALESCE(f.value:ADGROUP_ID_NETWORK::VARCHAR, 'unknown') AS ADGROUP_ID_NETWORK,
            COALESCE(f.value:ADGROUP_NETWORK::VARCHAR, 'unknown') AS ADGROUP_NETWORK,
            COALESCE(f.value:AD_ID::VARCHAR, 'unknown') AS AD_ID,
            COALESCE(f.value:AD_NAME::VARCHAR, 'unknown') AS AD_NAME,
            f.value:STORE_ID::VARCHAR AS STORE_ID,
            f.value:STORE_TYPE::VARCHAR AS STORE_TYPE,
            f.value:PLATFORM::VARCHAR AS PLATFORM,
            'USD' AS CURRENCY_CODE,
            'Adjust API' AS DATA_SOURCE_NAME,
            -- Standard Metrics
            f.value:INSTALLS::NUMBER AS INSTALLS,
            f.value:CLICKS::NUMBER AS CLICKS,
            f.value:IMPRESSIONS::NUMBER AS IMPRESSIONS,
            f.value:SESSIONS::NUMBER AS SESSIONS,
            f.value:BASE_SESSIONS::NUMBER AS BASE_SESSIONS,
            f.value:COST::FLOAT AS COST,
            f.value:ADJUST_COST::FLOAT AS ADJUST_COST,
            f.value:NETWORK_COST::FLOAT AS NETWORK_COST,
            f.value:REATTRIBUTIONS::NUMBER AS REATTRIBUTIONS,
            f.value:REATTRIBUTION_REINSTALLS::NUMBER AS REATTRIBUTION_REINSTALLS,
            f.value:REINSTALLS::NUMBER AS REINSTALLS,
            f.value:UNINSTALLS::NUMBER AS UNINSTALLS,
            f.value:DEATTRIBUTIONS::NUMBER AS DEATTRIBUTIONS,
            f.value:EVENTS::NUMBER AS EVENTS,
            f.value:PAID_CLICKS::NUMBER AS PAID_CLICKS,
            f.value:PAID_IMPRESSIONS::NUMBER AS PAID_IMPRESSIONS,
            f.value:PAID_INSTALLS::NUMBER AS PAID_INSTALLS,
            -- Custom Event Metrics
            f.value:C_DATASCAPE_BUNDLE_PURCHASE_EVENTS::NUMBER AS C_DATASCAPE_BUNDLE_PURCHASE_EVENTS,
            f.value:C_DATASCAPE_BUNDLE_PURCHASE_REVENUE::FLOAT AS C_DATASCAPE_BUNDLE_PURCHASE_REVENUE,
            f.value:C_DATASCAPE_COIN_PURCHASE_EVENTS::NUMBER AS C_DATASCAPE_COIN_PURCHASE_EVENTS,
            f.value:C_DATASCAPE_COIN_PURCHASE_REVENUE::FLOAT AS C_DATASCAPE_COIN_PURCHASE_REVENUE,
            f.value:C_DATASCAPE_CREDIT_PURCHASE_EVENTS::NUMBER AS C_DATASCAPE_CREDIT_PURCHASE_EVENTS,
            f.value:C_DATASCAPE_CREDIT_PURCHASE_REVENUE::FLOAT AS C_DATASCAPE_CREDIT_PURCHASE_REVENUE,
            f.value:C_DATASCAPE_PLAYFORCASHCLICK_EVENTS::NUMBER AS C_DATASCAPE_PLAYFORCASHCLICK_EVENTS,
            f.value:C_DATASCAPE_PLAYFORCASHCLICK_REVENUE::FLOAT AS C_DATASCAPE_PLAYFORCASHCLICK_REVENUE,
            f.value:C_DATASCAPE_REACHLEVEL_5_EVENTS::NUMBER AS C_DATASCAPE_REACHLEVEL_5_EVENTS,
            f.value:C_DATASCAPE_REACHLEVEL_5_REVENUE::FLOAT AS C_DATASCAPE_REACHLEVEL_5_REVENUE,
            f.value:C_DATASCAPE_REACHLEVEL_10_EVENTS::NUMBER AS C_DATASCAPE_REACHLEVEL_10_EVENTS,
            f.value:C_DATASCAPE_REACHLEVEL_10_REVENUE::FLOAT AS C_DATASCAPE_REACHLEVEL_10_REVENUE,
            f.value:C_DATASCAPE_REACHLEVEL_20_EVENTS::NUMBER AS C_DATASCAPE_REACHLEVEL_20_EVENTS,
            f.value:C_DATASCAPE_REACHLEVEL_20_REVENUE::FLOAT AS C_DATASCAPE_REACHLEVEL_20_REVENUE,
            f.value:C_DATASCAPE_REACHLEVEL_30_EVENTS::NUMBER AS C_DATASCAPE_REACHLEVEL_30_EVENTS,
            f.value:C_DATASCAPE_REACHLEVEL_30_REVENUE::FLOAT AS C_DATASCAPE_REACHLEVEL_30_REVENUE,
            f.value:C_DATASCAPE_REACHLEVEL_40_EVENTS::NUMBER AS C_DATASCAPE_REACHLEVEL_40_EVENTS,
            f.value:C_DATASCAPE_REACHLEVEL_40_REVENUE::FLOAT AS C_DATASCAPE_REACHLEVEL_40_REVENUE,
            f.value:C_DATASCAPE_REACHLEVEL_50_EVENTS::NUMBER AS C_DATASCAPE_REACHLEVEL_50_EVENTS,
            f.value:C_DATASCAPE_REACHLEVEL_50_REVENUE::FLOAT AS C_DATASCAPE_REACHLEVEL_50_REVENUE,
            f.value:C_DATASCAPE_REACHLEVEL_60_EVENTS::NUMBER AS C_DATASCAPE_REACHLEVEL_60_EVENTS,
            f.value:C_DATASCAPE_REACHLEVEL_60_REVENUE::FLOAT AS C_DATASCAPE_REACHLEVEL_60_REVENUE,
            f.value:C_DATASCAPE_REACHLEVEL_70_EVENTS::NUMBER AS C_DATASCAPE_REACHLEVEL_70_EVENTS,
            f.value:C_DATASCAPE_REACHLEVEL_70_REVENUE::FLOAT AS C_DATASCAPE_REACHLEVEL_70_REVENUE,
            f.value:C_DATASCAPE_REACHLEVEL_80_EVENTS::NUMBER AS C_DATASCAPE_REACHLEVEL_80_EVENTS,
            f.value:C_DATASCAPE_REACHLEVEL_80_REVENUE::FLOAT AS C_DATASCAPE_REACHLEVEL_80_REVENUE,
            f.value:C_DATASCAPE_REACHLEVEL_90_EVENTS::NUMBER AS C_DATASCAPE_REACHLEVEL_90_EVENTS,
            f.value:C_DATASCAPE_REACHLEVEL_90_REVENUE::FLOAT AS C_DATASCAPE_REACHLEVEL_90_REVENUE,
            f.value:C_DATASCAPE_REACHLEVEL_100_EVENTS::NUMBER AS C_DATASCAPE_REACHLEVEL_100_EVENTS,
            f.value:C_DATASCAPE_REACHLEVEL_100_REVENUE::FLOAT AS C_DATASCAPE_REACHLEVEL_100_REVENUE,
            f.value:C_DATASCAPE_REACHLEVEL_110_EVENTS::NUMBER AS C_DATASCAPE_REACHLEVEL_110_EVENTS,
            f.value:C_DATASCAPE_REACHLEVEL_110_REVENUE::FLOAT AS C_DATASCAPE_REACHLEVEL_110_REVENUE,
            f.value:C_DATASCAPE_REGISTRATION_EVENTS::NUMBER AS C_DATASCAPE_REGISTRATION_EVENTS,
            f.value:C_DATASCAPE_TUTORIAL_COMPLETED_EVENTS::NUMBER AS C_DATASCAPE_TUTORIAL_COMPLETED_EVENTS,
            f.value:C_DATASCAPE_TUTORIAL_COMPLETED_REVENUE::FLOAT AS C_DATASCAPE_TUTORIAL_COMPLETED_REVENUE
        FROM WGT.ADJUST_API.ADJ_CAMPAIGN_API_STAGING s,
             LATERAL FLATTEN(input => PARSE_JSON(s.RAW_JSON:rows)) f
        WHERE s.API_CALL_DATE = :p_date
          AND s.RAW_JSON:error IS NULL
    ) AS source
    ON target.DATE = source.DATE
       AND target.APP = source.APP
       AND target.OS_NAME = source.OS_NAME
       AND target.COUNTRY_CODE = source.COUNTRY_CODE
       AND target.PARTNER_ID = source.PARTNER_ID
       AND target.CAMPAIGN_ID_NETWORK = source.CAMPAIGN_ID_NETWORK
       AND target.ADGROUP_ID_NETWORK = source.ADGROUP_ID_NETWORK
       AND target.AD_ID = source.AD_ID
    WHEN MATCHED THEN UPDATE SET
        target.AD_NAME = source.AD_NAME,
        target.ADGROUP_NETWORK = source.ADGROUP_NETWORK,
        target.CAMPAIGN_NETWORK = source.CAMPAIGN_NETWORK,
        target.COUNTRY = source.COUNTRY,
        target.DEVICE_TYPE = source.DEVICE_TYPE,
        target.PARTNER_NAME = source.PARTNER_NAME,
        target.REGION = source.REGION,
        target.STORE_ID = source.STORE_ID,
        target.STORE_TYPE = source.STORE_TYPE,
        target.PLATFORM = source.PLATFORM,
        target.INSTALLS = source.INSTALLS,
        target.CLICKS = source.CLICKS,
        target.IMPRESSIONS = source.IMPRESSIONS,
        target.SESSIONS = source.SESSIONS,
        target.BASE_SESSIONS = source.BASE_SESSIONS,
        target.COST = source.COST,
        target.ADJUST_COST = source.ADJUST_COST,
        target.NETWORK_COST = source.NETWORK_COST,
        target.REATTRIBUTIONS = source.REATTRIBUTIONS,
        target.REATTRIBUTION_REINSTALLS = source.REATTRIBUTION_REINSTALLS,
        target.REINSTALLS = source.REINSTALLS,
        target.UNINSTALLS = source.UNINSTALLS,
        target.DEATTRIBUTIONS = source.DEATTRIBUTIONS,
        target.EVENTS = source.EVENTS,
        target.PAID_CLICKS = source.PAID_CLICKS,
        target.PAID_IMPRESSIONS = source.PAID_IMPRESSIONS,
        target.PAID_INSTALLS = source.PAID_INSTALLS,
        target.C_DATASCAPE_BUNDLE_PURCHASE_EVENTS = source.C_DATASCAPE_BUNDLE_PURCHASE_EVENTS,
        target.C_DATASCAPE_BUNDLE_PURCHASE_REVENUE = source.C_DATASCAPE_BUNDLE_PURCHASE_REVENUE,
        target.C_DATASCAPE_COIN_PURCHASE_EVENTS = source.C_DATASCAPE_COIN_PURCHASE_EVENTS,
        target.C_DATASCAPE_COIN_PURCHASE_REVENUE = source.C_DATASCAPE_COIN_PURCHASE_REVENUE,
        target.C_DATASCAPE_CREDIT_PURCHASE_EVENTS = source.C_DATASCAPE_CREDIT_PURCHASE_EVENTS,
        target.C_DATASCAPE_CREDIT_PURCHASE_REVENUE = source.C_DATASCAPE_CREDIT_PURCHASE_REVENUE,
        target.C_DATASCAPE_PLAYFORCASHCLICK_EVENTS = source.C_DATASCAPE_PLAYFORCASHCLICK_EVENTS,
        target.C_DATASCAPE_PLAYFORCASHCLICK_REVENUE = source.C_DATASCAPE_PLAYFORCASHCLICK_REVENUE,
        target.C_DATASCAPE_REACHLEVEL_5_EVENTS = source.C_DATASCAPE_REACHLEVEL_5_EVENTS,
        target.C_DATASCAPE_REACHLEVEL_5_REVENUE = source.C_DATASCAPE_REACHLEVEL_5_REVENUE,
        target.C_DATASCAPE_REACHLEVEL_10_EVENTS = source.C_DATASCAPE_REACHLEVEL_10_EVENTS,
        target.C_DATASCAPE_REACHLEVEL_10_REVENUE = source.C_DATASCAPE_REACHLEVEL_10_REVENUE,
        target.C_DATASCAPE_REACHLEVEL_20_EVENTS = source.C_DATASCAPE_REACHLEVEL_20_EVENTS,
        target.C_DATASCAPE_REACHLEVEL_20_REVENUE = source.C_DATASCAPE_REACHLEVEL_20_REVENUE,
        target.C_DATASCAPE_REACHLEVEL_30_EVENTS = source.C_DATASCAPE_REACHLEVEL_30_EVENTS,
        target.C_DATASCAPE_REACHLEVEL_30_REVENUE = source.C_DATASCAPE_REACHLEVEL_30_REVENUE,
        target.C_DATASCAPE_REACHLEVEL_40_EVENTS = source.C_DATASCAPE_REACHLEVEL_40_EVENTS,
        target.C_DATASCAPE_REACHLEVEL_40_REVENUE = source.C_DATASCAPE_REACHLEVEL_40_REVENUE,
        target.C_DATASCAPE_REACHLEVEL_50_EVENTS = source.C_DATASCAPE_REACHLEVEL_50_EVENTS,
        target.C_DATASCAPE_REACHLEVEL_50_REVENUE = source.C_DATASCAPE_REACHLEVEL_50_REVENUE,
        target.C_DATASCAPE_REACHLEVEL_60_EVENTS = source.C_DATASCAPE_REACHLEVEL_60_EVENTS,
        target.C_DATASCAPE_REACHLEVEL_60_REVENUE = source.C_DATASCAPE_REACHLEVEL_60_REVENUE,
        target.C_DATASCAPE_REACHLEVEL_70_EVENTS = source.C_DATASCAPE_REACHLEVEL_70_EVENTS,
        target.C_DATASCAPE_REACHLEVEL_70_REVENUE = source.C_DATASCAPE_REACHLEVEL_70_REVENUE,
        target.C_DATASCAPE_REACHLEVEL_80_EVENTS = source.C_DATASCAPE_REACHLEVEL_80_EVENTS,
        target.C_DATASCAPE_REACHLEVEL_80_REVENUE = source.C_DATASCAPE_REACHLEVEL_80_REVENUE,
        target.C_DATASCAPE_REACHLEVEL_90_EVENTS = source.C_DATASCAPE_REACHLEVEL_90_EVENTS,
        target.C_DATASCAPE_REACHLEVEL_90_REVENUE = source.C_DATASCAPE_REACHLEVEL_90_REVENUE,
        target.C_DATASCAPE_REACHLEVEL_100_EVENTS = source.C_DATASCAPE_REACHLEVEL_100_EVENTS,
        target.C_DATASCAPE_REACHLEVEL_100_REVENUE = source.C_DATASCAPE_REACHLEVEL_100_REVENUE,
        target.C_DATASCAPE_REACHLEVEL_110_EVENTS = source.C_DATASCAPE_REACHLEVEL_110_EVENTS,
        target.C_DATASCAPE_REACHLEVEL_110_REVENUE = source.C_DATASCAPE_REACHLEVEL_110_REVENUE,
        target.C_DATASCAPE_REGISTRATION_EVENTS = source.C_DATASCAPE_REGISTRATION_EVENTS,
        target.C_DATASCAPE_TUTORIAL_COMPLETED_EVENTS = source.C_DATASCAPE_TUTORIAL_COMPLETED_EVENTS,
        target.C_DATASCAPE_TUTORIAL_COMPLETED_REVENUE = source.C_DATASCAPE_TUTORIAL_COMPLETED_REVENUE,
        target.LOADED_AT = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (
        DATE, APP, OS_NAME, DEVICE_TYPE, COUNTRY, COUNTRY_CODE, REGION,
        PARTNER_ID, PARTNER_NAME, CAMPAIGN_ID_NETWORK, CAMPAIGN_NETWORK,
        ADGROUP_ID_NETWORK, ADGROUP_NETWORK, AD_ID, AD_NAME,
        STORE_ID, STORE_TYPE, PLATFORM, CURRENCY_CODE, DATA_SOURCE_NAME,
        INSTALLS, CLICKS, IMPRESSIONS, SESSIONS, BASE_SESSIONS,
        COST, ADJUST_COST, NETWORK_COST, REATTRIBUTIONS, REATTRIBUTION_REINSTALLS,
        REINSTALLS, UNINSTALLS, DEATTRIBUTIONS, EVENTS,
        PAID_CLICKS, PAID_IMPRESSIONS, PAID_INSTALLS,
        C_DATASCAPE_BUNDLE_PURCHASE_EVENTS, C_DATASCAPE_BUNDLE_PURCHASE_REVENUE,
        C_DATASCAPE_COIN_PURCHASE_EVENTS, C_DATASCAPE_COIN_PURCHASE_REVENUE,
        C_DATASCAPE_CREDIT_PURCHASE_EVENTS, C_DATASCAPE_CREDIT_PURCHASE_REVENUE,
        C_DATASCAPE_PLAYFORCASHCLICK_EVENTS, C_DATASCAPE_PLAYFORCASHCLICK_REVENUE,
        C_DATASCAPE_REACHLEVEL_5_EVENTS, C_DATASCAPE_REACHLEVEL_5_REVENUE,
        C_DATASCAPE_REACHLEVEL_10_EVENTS, C_DATASCAPE_REACHLEVEL_10_REVENUE,
        C_DATASCAPE_REACHLEVEL_20_EVENTS, C_DATASCAPE_REACHLEVEL_20_REVENUE,
        C_DATASCAPE_REACHLEVEL_30_EVENTS, C_DATASCAPE_REACHLEVEL_30_REVENUE,
        C_DATASCAPE_REACHLEVEL_40_EVENTS, C_DATASCAPE_REACHLEVEL_40_REVENUE,
        C_DATASCAPE_REACHLEVEL_50_EVENTS, C_DATASCAPE_REACHLEVEL_50_REVENUE,
        C_DATASCAPE_REACHLEVEL_60_EVENTS, C_DATASCAPE_REACHLEVEL_60_REVENUE,
        C_DATASCAPE_REACHLEVEL_70_EVENTS, C_DATASCAPE_REACHLEVEL_70_REVENUE,
        C_DATASCAPE_REACHLEVEL_80_EVENTS, C_DATASCAPE_REACHLEVEL_80_REVENUE,
        C_DATASCAPE_REACHLEVEL_90_EVENTS, C_DATASCAPE_REACHLEVEL_90_REVENUE,
        C_DATASCAPE_REACHLEVEL_100_EVENTS, C_DATASCAPE_REACHLEVEL_100_REVENUE,
        C_DATASCAPE_REACHLEVEL_110_EVENTS, C_DATASCAPE_REACHLEVEL_110_REVENUE,
        C_DATASCAPE_REGISTRATION_EVENTS,
        C_DATASCAPE_TUTORIAL_COMPLETED_EVENTS, C_DATASCAPE_TUTORIAL_COMPLETED_REVENUE
    ) VALUES (
        source.DATE, source.APP, source.OS_NAME, source.DEVICE_TYPE, source.COUNTRY,
        source.COUNTRY_CODE, source.REGION, source.PARTNER_ID, source.PARTNER_NAME,
        source.CAMPAIGN_ID_NETWORK, source.CAMPAIGN_NETWORK, source.ADGROUP_ID_NETWORK,
        source.ADGROUP_NETWORK, source.AD_ID, source.AD_NAME, source.STORE_ID,
        source.STORE_TYPE, source.PLATFORM, source.CURRENCY_CODE, source.DATA_SOURCE_NAME,
        source.INSTALLS, source.CLICKS, source.IMPRESSIONS, source.SESSIONS, source.BASE_SESSIONS,
        source.COST, source.ADJUST_COST, source.NETWORK_COST, source.REATTRIBUTIONS,
        source.REATTRIBUTION_REINSTALLS, source.REINSTALLS, source.UNINSTALLS,
        source.DEATTRIBUTIONS, source.EVENTS, source.PAID_CLICKS, source.PAID_IMPRESSIONS,
        source.PAID_INSTALLS,
        source.C_DATASCAPE_BUNDLE_PURCHASE_EVENTS, source.C_DATASCAPE_BUNDLE_PURCHASE_REVENUE,
        source.C_DATASCAPE_COIN_PURCHASE_EVENTS, source.C_DATASCAPE_COIN_PURCHASE_REVENUE,
        source.C_DATASCAPE_CREDIT_PURCHASE_EVENTS, source.C_DATASCAPE_CREDIT_PURCHASE_REVENUE,
        source.C_DATASCAPE_PLAYFORCASHCLICK_EVENTS, source.C_DATASCAPE_PLAYFORCASHCLICK_REVENUE,
        source.C_DATASCAPE_REACHLEVEL_5_EVENTS, source.C_DATASCAPE_REACHLEVEL_5_REVENUE,
        source.C_DATASCAPE_REACHLEVEL_10_EVENTS, source.C_DATASCAPE_REACHLEVEL_10_REVENUE,
        source.C_DATASCAPE_REACHLEVEL_20_EVENTS, source.C_DATASCAPE_REACHLEVEL_20_REVENUE,
        source.C_DATASCAPE_REACHLEVEL_30_EVENTS, source.C_DATASCAPE_REACHLEVEL_30_REVENUE,
        source.C_DATASCAPE_REACHLEVEL_40_EVENTS, source.C_DATASCAPE_REACHLEVEL_40_REVENUE,
        source.C_DATASCAPE_REACHLEVEL_50_EVENTS, source.C_DATASCAPE_REACHLEVEL_50_REVENUE,
        source.C_DATASCAPE_REACHLEVEL_60_EVENTS, source.C_DATASCAPE_REACHLEVEL_60_REVENUE,
        source.C_DATASCAPE_REACHLEVEL_70_EVENTS, source.C_DATASCAPE_REACHLEVEL_70_REVENUE,
        source.C_DATASCAPE_REACHLEVEL_80_EVENTS, source.C_DATASCAPE_REACHLEVEL_80_REVENUE,
        source.C_DATASCAPE_REACHLEVEL_90_EVENTS, source.C_DATASCAPE_REACHLEVEL_90_REVENUE,
        source.C_DATASCAPE_REACHLEVEL_100_EVENTS, source.C_DATASCAPE_REACHLEVEL_100_REVENUE,
        source.C_DATASCAPE_REACHLEVEL_110_EVENTS, source.C_DATASCAPE_REACHLEVEL_110_REVENUE,
        source.C_DATASCAPE_REGISTRATION_EVENTS,
        source.C_DATASCAPE_TUTORIAL_COMPLETED_EVENTS, source.C_DATASCAPE_TUTORIAL_COMPLETED_REVENUE
    );

    -- Get row count
    SELECT COUNT(*) INTO v_rows_loaded
    FROM WGT.ADJUST_API.ADJ_CAMPAIGN_API
    WHERE DATE = :p_date AND APP = :p_app_name;

    -- Log the load
    INSERT INTO WGT.ADJUST_API.API_LOAD_LOG (
        LOAD_DATE, APP_NAME, STATUS, ROWS_LOADED, STARTED_AT, COMPLETED_AT, DURATION_SECONDS
    ) VALUES (
        :p_date,
        :p_app_name,
        'SUCCESS',
        :v_rows_loaded,
        :v_start_time,
        CURRENT_TIMESTAMP(),
        DATEDIFF('second', :v_start_time, CURRENT_TIMESTAMP())
    );

    -- Clean up staging
    DELETE FROM WGT.ADJUST_API.ADJ_CAMPAIGN_API_STAGING
    WHERE API_CALL_DATE = :p_date;

    RETURN 'SUCCESS: Loaded ' || v_rows_loaded || ' rows for ' || p_app_name || ' on ' || p_date;

EXCEPTION
    WHEN OTHER THEN
        v_error_message := SQLERRM;

        INSERT INTO WGT.ADJUST_API.API_LOAD_LOG (
            LOAD_DATE, APP_NAME, STATUS, ERROR_MESSAGE, STARTED_AT, COMPLETED_AT
        ) VALUES (
            :p_date, :p_app_name, 'ERROR', :v_error_message, :v_start_time, CURRENT_TIMESTAMP()
        );

        RETURN 'ERROR: ' || v_error_message;
END;
$$;

-- ============================================================================
-- 2. PROCEDURE: Daily Load for All Apps
-- ============================================================================

CREATE OR REPLACE PROCEDURE load_adjust_daily()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    v_load_date DATE;
    v_result VARCHAR;
    v_final_result VARCHAR DEFAULT '';
    c_apps CURSOR FOR
        SELECT APP_NAME, APP_TOKEN
        FROM WGT.ADJUST_API.APP_TOKEN_MAPPING
        WHERE IS_ACTIVE = TRUE;
BEGIN
    -- Load yesterday's data (T-1)
    v_load_date := DATEADD('day', -1, CURRENT_DATE());

    FOR app IN c_apps DO
        CALL load_adjust_data_for_date(:v_load_date, app.APP_TOKEN, app.APP_NAME);
        v_result := (SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));
        v_final_result := v_final_result || app.APP_NAME || ': ' || v_result || '; ';
    END FOR;

    RETURN v_final_result;
END;
$$;

-- ============================================================================
-- 3. PROCEDURE: Backfill Date Range
-- ============================================================================

CREATE OR REPLACE PROCEDURE backfill_adjust_data(
    p_start_date DATE,
    p_end_date DATE
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    v_current_date DATE;
    v_result VARCHAR;
    v_total_days INTEGER DEFAULT 0;
    c_apps CURSOR FOR
        SELECT APP_NAME, APP_TOKEN
        FROM WGT.ADJUST_API.APP_TOKEN_MAPPING
        WHERE IS_ACTIVE = TRUE;
BEGIN
    v_current_date := p_start_date;

    WHILE (v_current_date <= p_end_date) DO
        FOR app IN c_apps DO
            CALL load_adjust_data_for_date(:v_current_date, app.APP_TOKEN, app.APP_NAME);
        END FOR;

        v_total_days := v_total_days + 1;
        v_current_date := DATEADD('day', 1, v_current_date);
    END WHILE;

    RETURN 'Backfill complete. Processed ' || v_total_days || ' days from ' || p_start_date || ' to ' || p_end_date;
END;
$$;

-- Grant execute permissions
GRANT USAGE ON PROCEDURE load_adjust_data_for_date(DATE, VARCHAR, VARCHAR) TO ROLE DBT_ROLE;
GRANT USAGE ON PROCEDURE load_adjust_daily() TO ROLE DBT_ROLE;
GRANT USAGE ON PROCEDURE backfill_adjust_data(DATE, DATE) TO ROLE DBT_ROLE;
